import type { WisePerson, Work, Question, BookList } from "@/types"

// ========== 著作 ==========
export const mockWorks: Work[] = [
  // [0] w-1
  {
    id: "w-1",
    slug: "the-republic",
    title: "理想国",
    authorName: "柏拉图",
    summary: "柏拉图的代表作，以对话体形式探讨正义、理想城邦与哲学王的思想。",
    description: "《理想国》是柏拉图最著名的作品，以苏格拉底为主角的对话体著作。全书共十卷，探讨了正义的本质、理想城邦的构建、哲学王的统治、理念论、教育理论等核心哲学问题。",
    recommendation: "西方哲学的奠基之作，理解柏拉图思想的必读经典。",
    genre: "monograph",
    category: "core",
  },
  // [1] w-2
  {
    id: "w-2",
    slug: "critique-of-pure-reason",
    title: "纯粹理性批判",
    authorName: "康德",
    summary: "康德的代表作，探讨人类理性的边界与可能性，开创了先验唯心论哲学。",
    description: "《纯粹理性批判》是康德哲学的代表作，也是西方哲学史上最重要的著作之一。书中康德系统地考察了人类理性的能力与界限，提出了「先天综合判断」的概念，试图调和理性主义与经验主义的对立。",
    recommendation: "了解康德哲学乃至整个德国古典哲学的入门钥匙。",
    genre: "monograph",
    category: "core",
  },
  // [2] w-3
  {
    id: "w-3",
    slug: "the-origin-of-species",
    title: "物种起源",
    authorName: "达尔文",
    summary: "达尔文的划时代著作，提出自然选择理论，改变了人类对生命演化的认知。",
    description: "《物种起源》是达尔文的代表作，书中系统阐述了自然选择理论，论证了物种通过变异和自然选择逐渐演化的过程。这本书彻底改变了人类对生命起源和演化的理解。",
    recommendation: "改变世界科学观的里程碑式著作。",
    genre: "monograph",
    category: "core",
  },
  // [3] w-4
  {
    id: "w-4",
    slug: "dream-of-the-red-chamber",
    title: "红楼梦",
    authorName: "曹雪芹",
    summary: "中国古典文学的巅峰之作，以贾府的兴衰为背景，展现了封建社会的百态人生。",
    description: "《红楼梦》以贾宝玉、林黛玉、薛宝钗的爱情悲剧为主线，通过对贾、史、王、薛四大家族兴衰的描写，展现了18世纪中国封建社会的广阔画卷。",
    recommendation: "中国文学史上最伟大的小说之一，值得反复品读。",
    genre: "monograph",
    category: "core",
  },
  // [4] w-5
  {
    id: "w-5",
    slug: "tao-te-ching",
    title: "道德经",
    authorName: "老子",
    summary: "道家思想的根本经典，以简洁深邃的语言探讨「道」与「德」的哲学内涵。",
    description: "《道德经》又称《老子》，是道家哲学最重要的经典。全书仅五千余字，分为八十一章，以精炼的语言阐述了「道」作为宇宙本源和运行规律的哲学思想。",
    recommendation: "中国哲学史上最具影响力的经典之一，字字珠玑。",
    genre: "monograph",
    category: "core",
  },
  // [5] w-6
  {
    id: "w-6",
    slug: "on-the-origin-of-inequality",
    title: "论人类不平等的起源",
    authorName: "卢梭",
    summary: "卢梭探讨人类社会不平等起源的经典著作，对现代政治哲学影响深远。",
    description: "《论人类不平等的起源》是卢梭应第戎科学院的征文而作。卢梭在书中探讨了人类从自然状态到社会状态的转变过程，以及私有制的产生如何导致了社会不平等。",
    recommendation: "理解社会契约论和现代民主思想的重要基础。",
    genre: "monograph",
    category: "core",
  },
  // [6] w-7
  {
    id: "w-7",
    slug: "das-kapital",
    title: "资本论",
    authorName: "马克思",
    summary: "马克思的代表作，系统阐述了剩余价值理论和资本主义经济危机理论。",
    description: "《资本论》是马克思的代表作，第一卷于1867年出版。书中系统阐述了剩余价值理论，揭示了资本主义剥削的秘密，论证了资本主义经济危机的必然性。",
    recommendation: "理解马克思主义经济学的核心著作。",
    genre: "monograph",
    category: "core",
  },
  // [7] w-8
  {
    id: "w-8",
    slug: "communist-manifesto",
    title: "共产党宣言",
    authorName: "马克思、恩格斯",
    summary: "马克思主义的纲领性文件，阐述了阶级斗争理论和共产主义理想。",
    description: "《共产党宣言》是马克思和恩格斯合著的著作，发表于1848年。书中阐述了历史唯物主义的基本原理，提出了阶级斗争理论，号召「全世界无产者，联合起来！」",
    recommendation: "理解马克思主义的入门读物。",
    genre: "monograph",
    category: "core",
  },
  // [8] w-9
  {
    id: "w-9",
    slug: "the-protestant-ethic",
    title: "新教伦理与资本主义精神",
    authorName: "马克斯·韦伯",
    summary: "韦伯的代表作，探讨新教伦理如何促进了资本主义精神的兴起。",
    description: "《新教伦理与资本主义精神》是马克斯·韦伯的代表作，发表于1904-1905年。韦伯在书中论证：加尔文主义的「天职」观念和入世禁欲主义，为资本主义精神的兴起提供了伦理基础。",
    recommendation: "理解文化因素如何影响经济发展的经典著作。",
    genre: "monograph",
    category: "core",
  },
  // [9] w-10
  {
    id: "w-10",
    slug: "the-wealth-of-nations",
    title: "国富论",
    authorName: "亚当·斯密",
    summary: "亚当·斯密的代表作，古典经济学的奠基之作。",
    description: "《国富论》全名《国民财富的性质和原因的研究》，是亚当·斯密的代表作，发表于1776年。书中系统阐述了劳动价值论、分工理论和自由市场经济的重要性。",
    recommendation: "理解古典经济学的必读经典。",
    genre: "monograph",
    category: "core",
  },
  // [10] w-11
  {
    id: "w-11",
    slug: "social-contract",
    title: "社会契约论",
    authorName: "卢梭",
    summary: "卢梭的代表作，阐述社会契约理论和人民主权思想。",
    description: "《社会契约论》是卢梭的代表作，发表于1762年。书中提出了「公意」理论和「人生而自由，却无往不在枷锁之中」的著名论断，深刻影响了现代民主思想。",
    recommendation: "理解现代政治哲学的必读经典。",
    genre: "monograph",
    category: "core",
  },
]

// ========== 智者 ==========
export const mockWisePersons: WisePerson[] = [
  {
    id: "wp-1",
    slug: "plato",
    name: "柏拉图",
    nameEn: "Plato",
    summary: "古希腊哲学家，雅典人，其著作大多以对话录形式纪录，并创办了著名的柏拉图学院。柏拉图是苏格拉底的学生，亚里士多德的老师，他们三人被普遍认为是西方哲学的奠基人，史称「希腊三哲」。",
    biography: "柏拉图（约公元前427年—前347年）是古希腊最重要的哲学家之一，苏格拉底的学生，亚里士多德的老师。他在雅典创办了柏拉图学园，开创了西方哲学的传统。其哲学体系以「理念论」为核心，认为现实世界是对永恒理念世界的模仿。",
    coreThoughts: "理念论：认为物质世界是流动不居的，而理念世界才是永恒真实的。理想国：提出哲人王统治的理想城邦模型。灵魂不朽说：论证灵魂先于身体存在且在死后继续存在。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "理念论", "理想国"],
    works: [mockWorks[0]],
    relatedWisePersonSlugs: ["aristotle", "socrates"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E6%9F%8F%E6%8B%89%E5%9B%BE",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Plato", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/plato/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/plato/", description: "系统的哲学百科条目" },
      { label: "Perseus Digital Library", url: "http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0172", description: "著作原文与英译对照" },
    ],
        personalIntroduction: "柏拉图是西方哲学史上第一位建立完整体系的 thinker，其「理念论」认为我们感知的物质世界只是永恒理念世界的投影。这一思想深刻影响了后世两千多年的哲学走向，也为我们理解「知识的知识」（Q01）提供了最原初的框架：知识与真理的最终对象不是流变的现象，而是不变的理型。在通识学习中，柏拉图提醒我们——在具体学科知识之外，存在着更为根本的关于「什么是真实」「什么是正义」「什么是美好」的追问。他的《理想国》不仅是一本政治哲学著作，更是一张引导人从洞穴走向光明的教育地图。",
    questionNumbers: [1],
    topicCodes: ["1.1"],
  },
  {
    id: "wp-2",
    slug: "immanuel-kant",
    name: "康德",
    nameEn: "Immanuel Kant",
    summary: "启蒙时代德意志哲学家，德国古典哲学创始人。其学说影响近代西方哲学，开创了德国唯心主义和康德义务主义等流派。他调和了笛卡儿的理性主义与培根的经验主义，被视为继苏格拉底、柏拉图和亚里士多德之后西方最具影响力的思想家之一。",
    biography: "伊曼努尔·康德（1724—1804）是德国古典哲学的创始人，也是整个西方哲学史上最重要的哲学家之一。他一生从未离开过哥尼斯堡，但其思想却深刻影响了整个世界。他以三大批判——《纯粹理性批判》《实践理性批判》《判断力批判》——构建了完整的批判哲学体系。",
    coreThoughts: "哥白尼式革命：不是知识必须符合对象，而是对象必须符合我们的认识形式。绝对命令：道德律令是普遍的、必然的，不依赖于任何条件。人为自然立法：知性为自然颁布规律。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["德国古典哲学", "批判哲学", "启蒙运动"],
    works: [mockWorks[1]],
    relatedWisePersonSlugs: ["plato", "rousseau"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%BA%B7%E5%BE%B7",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Immanuel_Kant", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/kant/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/kantview/", description: "系统的哲学百科条目" },
    ],
        personalIntroduction: "康德在哲学史上完成了一次「哥白尼式革命」——不是知识必须符合对象，而是对象必须符合我们的认识形式。这一洞见彻底改变了我们对人类理性边界的理解，也为「知识的知识」（Q01）提供了认识论的基石。康德的三大批判构建了一套完整的哲学体系：我们如何知道（纯粹理性批判）、我们应当如何行动（实践理性批判）、以及我们如何感受美与目的（判断力批判）。在通识学习中，康德是一座绕不开的山峰——他教会我们以批判性思维审视一切知识的边界与条件，在理性与信仰之间划定清晰的界限。",
    questionNumbers: [1],
    topicCodes: ["1.1"],
  },
  {
    id: "wp-3",
    slug: "charles-darwin",
    name: "达尔文",
    nameEn: "Charles Darwin",
    summary: "英国博物学家、地质学家和生物学家，最著名的贡献是自然选择演化理论。他认为所有物种都是从少数共同祖先演化而来的，其理论成为演化机制的主要解释，奠定了现代演化思想的基础，被誉为「现今生物学的基石」。",
    biography: "查尔斯·达尔文（1809—1882）是英国博物学家，进化生物学的奠基人。他随贝格尔号进行了五年的环球考察，收集了大量生物和地质样本。基于这些观察，他提出了以自然选择为核心的进化理论。",
    coreThoughts: "自然选择：物种通过自然选择适应环境，适者生存。共同祖先：所有生命形式来自共同祖先。渐变论：进化是缓慢而渐进的过程。",
    era: "modern",
    discipline: "science",
    region: "western",
    tags: ["进化论", "自然选择", "生物学"],
    works: [mockWorks[2]],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%BE%BE%E5%B0%94%E6%96%87",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Charles_Darwin", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/darwin/", description: "权威的学术性哲学分析" },
      { label: "Darwin Online", url: "https://darwin-online.org.uk/", description: "达尔文全部著作的数字化档案" },
    ],
        personalIntroduction: "达尔文的进化论不只是生物学的一个分支理论，它是一场世界观的革命。在达尔文之前，人们相信物种是独立创造、永恒不变的；达尔文之后，我们认识到所有生命——包括人类——都来自共同的祖先，通过自然选择在漫长的岁月中演化而来。这一思想深刻影响了「如何理解世界」（Q02）这一根本问题：世界不是静止的、被设计的，而是动态的、演化的。达尔文教会我们以演化的眼光看待一切——从生物到社会、从文化到思想，变化与适应才是永恒的常态。在通识教育的框架中，演化思维是一种跨学科的认知工具。",
    questionNumbers: [2],
    topicCodes: ["2.2"],
  },
  {
    id: "wp-4",
    slug: "cao-xueqin",
    name: "曹雪芹",
    nameEn: "Cao Xueqin",
    summary: "清朝小说家、诗人、画家，中国古典名著《红楼梦》的作者。生于江宁府（今南京），祖籍辽阳，清内务府正白旗包衣世家出身。",
    biography: "曹雪芹（约1715—约1763），名霑，字梦阮，号雪芹。清代著名文学家。他出身于江宁织造世家，幼年家道中落，晚年贫困潦倒。在困顿中创作了《红楼梦》，「批阅十载，增删五次」，留下了这部中国文学史上的不朽巨著。",
    coreThoughts: "现实主义创作：以自家身世为素材，真实再现封建社会的兴衰。人物塑造：塑造了众多性格鲜明的人物形象。悲剧意识：深刻地揭示了封建制度必然崩溃的历史命运。",
    era: "modern",
    discipline: "literature",
    region: "eastern",
    tags: ["中国古典文学", "红楼梦", "现实主义"],
    works: [mockWorks[3]],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E6%9B%B9%E9%9B%AA%E8%8A%B9",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Cao_Xueqin", description: "完整的生平与核心思想介绍" },
      { label: "曹雪芹资料中心", url: "http://caoxueqincc.com", description: "曹雪芹研究与红学资料中心" },
      { label: "豆瓣（红楼梦）", url: "https://book.douban.com/subject/1007305/", description: "豆瓣读书页面" },
    ],
        personalIntroduction: "曹雪芹的《红楼梦》是中国文学史上最伟大的作品之一，它不仅是一部小说，更是一部关于人性的百科全书。在「如何理解人性」（Q08）这一维度上，曹雪芹以惊人的深度刻画了人物的复杂性与命运的无常。他笔下的贾宝玉、林黛玉、薛宝钗等人物不再是善恶分明的类型，而是充满矛盾与困惑的真实个体。曹雪芹教会我们：理解人性需要同情心而非道德审判，需要洞察力而非简单归类。在通识学习的语境中，《红楼梦》是一座关于「人如何活着、如何爱着、如何失去」的文学丰碑。",
    questionNumbers: [8],
    topicCodes: ["8.5"],
  },
  {
    id: "wp-5",
    slug: "laozi",
    name: "老子",
    nameEn: "Laozi",
    summary: "中国春秋时代思想家，道家学派创始人。姓李名耳，字聃，曾担任周朝守藏室之史。其所著《老子》（又称《道德经》）是道家哲学的根本经典，被奉为道教最重要经典之一。",
    biography: "老子（约公元前6世纪），姓李名耳，字聃，春秋末期楚国人。曾任周朝守藏室之史（国家图书馆馆长）。后见周室衰微，西出函谷关，应关令尹喜之请，著《道德经》五千余言，后不知所终。",
    coreThoughts: "道法自然：「道」是宇宙万物的本源和运行规律。无为而治：不妄为，顺应自然规律。对立统一：有无相生，难易相成，福祸相依。",
    era: "ancient",
    discipline: "philosophy",
    region: "eastern",
    tags: ["道家", "无为", "自然"],
    works: [mockWorks[4]],
    relatedWisePersonSlugs: ["zhuangzi"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%80%81%E5%AD%90",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Laozi", description: "完整的生平与核心思想介绍" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/laozi/", description: "系统的哲学百科条目" },
      { label: "Chinese Text Project", url: "https://ctext.org/dao-de-jing", description: "古籍原文与白话翻译" },
    ],
        personalIntroduction: "老子是中国哲学史上最深邃的 thinker 之一，五千言的《道德经》以极简的语言触及了宇宙、人生与社会的根本问题。「道可道，非常道」——真正的智慧不可言说，却可以通过体悟来把握。老子的思想在通识教育中具有独特的价值：他提出的「无为而治」不是消极不作为，而是要求我们理解事物的自然规律，顺势而为而不妄为。在「知识的知识」（Q01）层面，老子提醒我们：最高明的认知不是积累信息，而是回归本源，理解大道运行的规律。他的对立统一思维——有无相生、难易相成——为后世提供了深刻的辩证智慧。",
    questionNumbers: [1,10],
    topicCodes: ["1.1", "10.3"],
  },
  {
    id: "wp-6",
    slug: "rousseau",
    name: "卢梭",
    nameEn: "Jean-Jacques Rousseau",
    summary: "启蒙时代法国哲学家、政治学家、教育学家、作曲家与浪漫主义文学家。其《论人类不平等的起源与基础》深刻地影响了西方哲学的发展；代表作《社会契约论》中所论述的人民主权及民主政治哲学思想，深远影响了启蒙运动、法国大革命以至现代政治与教育思想。",
    biography: "让-雅克·卢梭（1712—1778）是法国启蒙运动的重要思想家。他的政治哲学深刻影响了法国大革命和现代民主思想的发展。卢梭的思想核心是「人生而自由，却无往不在枷锁之中」。",
    coreThoughts: "社会契约论：人们通过社会契约组成共同体，主权在民。自然状态：人类在自然状态中是善良的，文明带来不平等。公意：强调共同体的普遍意志高于个人意志。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["启蒙运动", "社会契约", "民主"],
    works: [mockWorks[5], mockWorks[10]],
    relatedWisePersonSlugs: ["immanuel-kant"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%AE%A9-%E9%9B%85%E5%85%8B%C2%B7%E5%8D%A2%E6%A2%AD",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Jean-Jacques_Rousseau", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/rousseau/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/rousseau/", description: "系统的哲学百科条目" },
    ],
        personalIntroduction: "卢梭是启蒙运动中最具原创性的思想家之一，他对「如何理解社会」（Q05）这一问题的思考至今仍具有震撼力。《论人类不平等的起源》揭示了一个深刻的悖论：文明带来了进步，却也制造了不平等；社会契约应当保障自由，现实中却往往成为枷锁。卢梭的「人生而自由，却无往不在枷锁之中」是对现代人处境最精准的概括之一。在通识学习中，卢梭教会我们以批判的眼光审视社会制度——不把既有秩序当作理所当然，而是追问其合法性与正当性。他的思想是理解现代政治哲学不可绕过的起点。",
    questionNumbers: [5],
    topicCodes: ["5.4"],
  },
  {
    id: "wp-11",
    slug: "karl-marx",
    name: "卡尔·马克思",
    nameEn: "Karl Marx",
    summary: "德国哲学家、经济学家、革命家，马克思主义的创始人。其思想对20世纪的社会运动产生了深远影响。",
    biography: "卡尔·马克思（1818—1883）是德国哲学家、经济学家、革命家，马克思主义的创始人。他与恩格斯合著的《共产党宣言》和《资本论》深刻影响了20世纪的社会运动。",
    coreThoughts: "历史唯物主义：不是意识决定存在，而是社会存在决定意识。阶级斗争：至今一切社会的历史都是阶级斗争的历史。剩余价值：利润来自工人的剩余劳动。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["马克思主义", "阶级斗争", "剩余价值"],
    works: [mockWorks[6], mockWorks[7]],
    relatedWisePersonSlugs: ["max-weber", "adam-smith"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%8D%A1%E5%B0%94%C2%B7%E9%A9%AC%E5%85%8B%E6%80%9D",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Karl_Marx", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/marx/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/marx/", description: "系统的哲学百科条目" },
      { label: "Marxists Archive", url: "https://www.marxists.org/", description: "马克思/恩格斯著作全集" },
    ],
        personalIntroduction: "马克思是历史上最有影响力的思想家之一。他的阶级斗争理论和历史唯物主义彻底改变了我们理解社会的方式。在「如何理解社会」（Q05）这一维度，马克思提供了最犀利的分析工具：社会不是和谐的有机体，而是阶级斗争的战场；历史不是杂乱无章的事件串，而是生产方式演化的结果。",
    questionNumbers: [5],
    topicCodes: ["5.1"],
  },
  {
    id: "wp-12",
    slug: "max-weber",
    name: "马克斯·韦伯",
    nameEn: "Max Weber",
    summary: "德国社会学家、哲学家、政治经济学家，社会学三大奠基人之一。以《新教伦理与资本主义精神》闻名。",
    biography: "马克斯·韦伯（1864—1920）是德国社会学家、哲学家、政治经济学家，社会学三大奠基人之一。他的《新教伦理与资本主义精神》探讨了文化因素（特别是宗教）如何塑造经济现实。",
    coreThoughts: "理性化：现代社会的核心趋势，用计算取代传统。新教伦理：新教伦理促进了资本主义精神的兴起。理想类型：社会科学的研究方法。科层制：现代组织的必然命运。",
    era: "modern",
    discipline: "sociology",
    region: "western",
    tags: ["社会学", "理性化", "新教伦理"],
    works: [mockWorks[8]],
    relatedWisePersonSlugs: ["karl-marx"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E9%A9%AC%E5%85%8B%E6%96%AF%C2%B7%E9%9F%81%E4%BC%AF",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Max_Weber", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/weber/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/weber/", description: "系统的哲学百科条目" },
      { label: "Max Weber Studies", url: "https://maxweberstudies.org/", description: "韦伯研究学术期刊" },
    ],
        personalIntroduction: "韦伯是社会学三大奠基人之一（与马克思、涂尔干并列）。他在「如何理解社会」（Q05）维度上的独特贡献在于：他既看到经济因素的重要性，也强调文化、宗教、观念的独立作用。《新教伦理与资本主义精神》展示了观念如何塑造经济现实，这对我们理解不同文明的差异具有重要意义。",
    questionNumbers: [5],
    topicCodes: ["5.1"],
  },
  {
    id: "wp-13",
    slug: "adam-smith",
    name: "亚当·斯密",
    nameEn: "Adam Smith",
    summary: "苏格兰哲学家、经济学家，古典经济学创始人。以《国富论》《道德情操论》闻名。",
    biography: "亚当·斯密（1723—1790）是苏格兰哲学家、经济学家，古典经济学的创始人。他的《国富论》奠定了现代经济学的基础，《道德情操论》则探讨了人类道德判断的来源。",
    coreThoughts: "看不见的手：市场机制协调自利行为。同情心：人类有天然的同情能力。分工：提高生产力的关键。",
    era: "modern",
    discipline: "economics",
    region: "western",
    tags: ["古典经济学", "看不见的手", "同情心"],
    works: [mockWorks[9]],
    relatedWisePersonSlugs: ["karl-marx"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E4%BA%9A%E5%BD%93%C2%B7%E6%96%AF%E5%AF%86%E6%96%AF",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Adam_Smith", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/smith/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/smith/", description: "系统的哲学百科条目" },
      { label: "Adam Smith Institute", url: "https://www.adamsmith.org/", description: "亚当·斯密研究机构官网" },
    ],
        personalIntroduction: "亚当·斯密是古典经济学的创始人，但他也是道德哲学家。《国富论》中的「看不见的手」理论和《道德情操论》中的「同情心」理论共同构成了他对人性的完整理解。在「如何理解社会」（Q05）中，斯密提供了理解市场经济的基础：自利行为如何通过市场机制产生社会福利？市场经济需要什么道德基础？",
    questionNumbers: [5],
    topicCodes: ["5.2"],
  },
  {
    id: "wp-7",
    slug: "aristotle",
    name: "亚里士多德",
    nameEn: "Aristotle",
    summary: "古希腊哲学家，柏拉图的学生、亚历山大大帝的老师。他与柏拉图、苏格拉底并称西方哲学的奠基者，其著作构成了西方哲学最早的系统，涵盖道德、美学、逻辑、科学、政治及形而上学等领域，被誉为百科全书式的学者。",
    biography: "亚里士多德（公元前384—前322年）是古希腊最博学的哲学家，柏拉图的学生，亚历山大大帝的老师。他在雅典创办了吕克昂学园，其著作涵盖哲学、逻辑学、政治学、物理学、生物学、伦理学等几乎所有学科领域。",
    coreThoughts: "四因说：质料因、形式因、动力因、目的因解释一切事物的存在和变化。中庸之道：美德在于两个极端之间的中道。人是政治动物：人天生是城邦的动物，需要通过政治生活实现幸福。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "逻辑学", "形而上学"],
    works: [],
    relatedWisePersonSlugs: ["plato", "immanuel-kant"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E4%BA%9A%E9%87%8C%E5%A3%AB%E5%A4%9A%E5%BE%B7",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Aristotle", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/aristotle/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/aristotl/", description: "系统的哲学百科条目" },
      { label: "Perseus Digital Library", url: "http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0086", description: "著作原文与英译对照" },
    ],
        personalIntroduction: "亚里士多德是西方第一位百科全书式的学者，他几乎凭一己之力为后世西方知识体系奠定了基础。从逻辑学到物理学、从伦理学到政治学、从生物学到诗学——他的研究覆盖了人类知识的全部疆域。在通识教育的语境下，亚里士多德最重要的遗产是他的分类思维和因果分析方法：「四因说」提供了一个理解万物的通用框架——追问事物的质料、形式、动力和目的。他还提出了「人是政治动物」的命题，提醒我们：理解社会与组织（Q05、Q06）不能脱离人的天性。亚里士多德教会我们以系统化的方式思考世界——不是零散地获取知识，而是建立有机的知识结构。",
    questionNumbers: [1, 5],
    topicCodes: ["1.1", "5.1"],
  },
  {
    id: "wp-8",
    slug: "socrates",
    name: "苏格拉底",
    nameEn: "Socrates",
    summary: "古希腊哲学家，与柏拉图、亚里士多德并称「希腊三贤」。他未留下任何著作，其思想主要通过学生柏拉图的对话录流传后世。他以苏格拉底式反诘法引导人们反思知识与信念，被公认为西方哲学的奠基者之一。",
    biography: "苏格拉底（公元前469—前399年）是古希腊哲学家，西方哲学的奠基人之一。他没有留下任何著作，其思想主要通过学生柏拉图的对话录流传后世。他通过不断追问的方式引导人们反思自己的知识和信念，这种方法被称为「苏格拉底式反诘法」。",
    coreThoughts: "认识你自己：哲学的首要任务是认识自我。精神助产术：通过提问帮助他人产生知识。美德即知识：真正的美德基于对善的知识。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "辩证法", "伦理"],
    works: [],
    relatedWisePersonSlugs: ["plato", "aristotle"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%8B%8F%E6%A0%BC%E6%8B%89%E5%BA%95",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Socrates", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/socrates/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/socrates/", description: "系统的哲学百科条目" },
    ],
        personalIntroduction: "苏格拉底没有留下任何著作，却成为西方哲学最伟大的奠基人之一。他的方法——通过不断追问来暴露人们知识中的矛盾与盲区——被后世称为「苏格拉底式反诘法」。这种方法本身就是一种关于「知识的知识」（Q01）的实践：真正的智慧不是拥有答案，而是承认自己的无知。苏格拉底的「认识你自己」是哲学史上最深刻也最简洁的箴言。在通识学习中，苏格拉底精神意味着不盲从权威、不满足于表面答案、持续地质疑与反思。他的死——为捍卫独立思考而饮下毒酒——是对哲学精神最庄严的诠释。",
    questionNumbers: [1],
    topicCodes: ["1.1"],
  },
  {
    id: "wp-9",
    slug: "zhuangzi",
    name: "庄子",
    nameEn: "Zhuangzi",
    summary: "战国时期道家代表人物，继承并发展了老子思想，后世并称「老庄」。其著作《庄子》被尊为《南华经》。庄子文章想象丰富，以寓言故事阐述深刻的哲学思想。",
    biography: "庄子（约公元前369—前286年），名周，战国时期宋国蒙人。他是继老子之后道家思想最重要的代表人物，与老子并称「老庄」。庄子的文章想象丰富，文笔汪洋恣肆，以寓言故事的形式阐述深刻的哲学思想。",
    coreThoughts: "齐物论：万物在道的层面上是齐一的，没有是非、善恶的绝对区别。逍遥游：追求精神的绝对自由和超越。无用之用：看似无用的东西往往有更大的用途。",
    era: "ancient",
    discipline: "philosophy",
    region: "eastern",
    tags: ["道家", "逍遥", "齐物"],
    works: [],
    relatedWisePersonSlugs: ["laozi"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%BA%84%E5%AD%90",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Zhuangzi", description: "完整的生平与核心思想介绍" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/zhuangzi/", description: "系统的哲学百科条目" },
      { label: "Chinese Text Project", url: "https://ctext.org/zhuangzi", description: "古籍原文与白话翻译" },
    ],
        personalIntroduction: "庄子是继老子之后道家思想最伟大的代表，他以汪洋恣肆的想象力和深刻的哲学洞见，将道家思想推向了新的高度。在通识学习的语境中，庄子的价值在于他提供了一种超越世俗认知框架的思维方式：「齐物论」消解了是非对错的绝对界限，教会我们以更开阔的视野看待分歧；「逍遥游」则勾勒了一种精神绝对自由的理想状态。庄子的「无用之用」是对功利主义思维最深刻的批判——那些看似无用的东西，往往有不可替代的价值。在十问框架中，庄子帮助我们反思「知识的知识」（Q01）的另一面：有些真理不在逻辑推演中，而在直觉与体悟之中。",
    questionNumbers: [1,10],
    topicCodes: ["1.1", "10.3"],
  },
  {
    id: "wp-10",
    slug: "sigmuend-freud",
    name: "弗洛伊德",
    nameEn: "Sigmund Freud",
    summary: "奥地利心理学家、精神分析学创始人、哲学家。精神分析学是一种通过医患对话评估和治疗心理冲突的临床方法，他提出的潜意识理论、人格结构理论深刻影响了20世纪的心理学、文学、艺术和社会思想，被公认为20世纪最具影响力的思想家之一。",
    biography: "西格蒙德·弗洛伊德（1856—1939）是奥地利心理学家，精神分析学派的创始人。他提出的潜意识理论、人格结构理论（本我、自我、超我）和性心理发展理论，深刻影响了20世纪的心理学、文学、艺术和社会思想。",
    coreThoughts: "潜意识：人的心理活动大部分在潜意识层面进行，影响着我们的行为。人格结构：本我遵循快乐原则，自我遵循现实原则，超我遵循道德原则。梦的解析：梦是愿望的满足，是通往潜意识的皇家大道。",
    era: "modern",
    discipline: "psychology",
    region: "western",
    tags: ["精神分析", "潜意识", "心理学"],
    works: [],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%A5%BF%E6%A0%BC%E8%92%99%E5%BE%B7%C2%B7%E5%BC%97%E6%B4%9B%E4%BC%8A%E5%BE%B7",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Sigmund_Freud", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/freud/", description: "权威的学术性哲学分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/freud/", description: "系统的哲学百科条目" },
      { label: "LOC Freud Collection", url: "https://loc.gov/collections/sigmund-freud-papers/about-this-collection/", description: "国会图书馆弗洛伊德档案（2万+件数字化）" },
      { label: "Freud Museum London", url: "https://freudmuseum.org.uk", description: "弗洛伊德伦敦故居博物馆" },
    ],
        personalIntroduction: "弗洛伊德是20世纪最具影响力的思想家之一，他的精神分析学说彻底改变了我们理解「人性」（Q08）的方式。在弗洛伊德之前，人类相信自己是理性的、自知的；弗洛伊德告诉我们——意识只是冰山一角，潜意识中的欲望、冲突和压抑才是驱动行为的真正力量。他的人格结构理论（本我、自我、超我）为理解人的内在冲突提供了经典框架。在通识学习的语境中，弗洛伊德的意义不在于他的具体结论（许多已被修正），而在于他开启了一个根本性的追问：人真的了解自己吗？这个追问至今仍是心理学、文学和艺术的核心议题。",
    questionNumbers: [8],
    topicCodes: ["8.3"],
  },
  {
    id: "wp-14",
    slug: "james-march",
    name: "詹姆斯·马奇",
    nameEn: "James G. March",
    summary: "美国组织理论家、决策科学家，有限理性理论的共同奠基人，提出探索与利用、垃圾桶模型等经典概念，被公认为组织研究领域最具影响力的思想家之一。",
    biography: "詹姆斯·马奇（1928—2018）是美国组织理论家，与赫伯特·西蒙共同发展了有限理性理论。他在卡内基理工学院和斯坦福大学任教近半个世纪，横跨政治学、社会学、管理学、教育学、心理学五个学科。他的研究深刻揭示了人类和组织决策的非理性本质。",
    coreThoughts: "有限理性：人不是完全理性的决策机器，只能做满意而非最优决策。探索与利用：一切组织和个体都面临的根本张力。垃圾桶模型：组织决策是问题、方案、参与者、机会随机汇合的结果。经验的疆界：经验不是可靠的老师。",
    era: "contemporary",
    discipline: "social-science",
    region: "western",
    tags: ["组织理论", "决策科学", "有限理性", "探索与利用"],
    works: [],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://en.wikipedia.org/wiki/James_G._March",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/James_G._March", description: "完整的生平与核心思想介绍" },
      { label: "Stanford GSB", url: "https://www.gsb.stanford.edu/newsroom/school-news/james-g-march-professor-business-education-humanities-dies-90", description: "权威的学术性哲学分析" },
      { label: "SCANCOR", url: "https://scancor.org/person/james-g-march/", description: "斯堪的纳维亚组织研究联盟档案" },
      { label: "Semantic Scholar", url: "https://www.semanticscholar.org/author/James-G-March/1790311", description: "学术论文与引用数据" },
    ],
        personalIntroduction: "马奇是那种你很难直接听到名字，但无处不在的思想者。有限理性、探索与利用、垃圾桶模型——这些概念的源头都在他这里。他对人类决策的理解是直白的：人不是理性机器，组织不是理性系统，经验不是好老师。读马奇不会让你感到安慰，但会让你在面对复杂决策时，至少知道自己面对的是什么。在通识学习中，他是理解「组织」（Q06）的关键入口——他将组织从抽象概念还原为真实的人类行为综合体。",
    questionNumbers: [6],
    topicCodes: ["6.1"],
  },
  {
    id: "wp-15",
    slug: "kevin-kelly",
    name: "凯文·凯利",
    nameEn: "Kevin Kelly",
    summary: "《连线》杂志创始执行主编、技术哲学家和未来学家。提出技术元素论、1000个铁杆粉丝等概念，著有《失控》《必然》《科技想要什么》，被誉为互联网时代的先知。",
    biography: "凯文·凯利（1952—）不是传统意义上的学者，而是一位观察者、写作者和思想者。他参与创办了《连线》杂志，定义了数字时代的文化想象。他是虔诚的基督徒，也是技术乐观主义者——这两种身份在他的思想中并不矛盾，而是构成了理解技术的独特视角。",
    coreThoughts: "技术元素：技术是第七种生命存在方式，有自己的演化规律。必然的十二种力量：某些技术大势不可逆转。1000个铁杆粉丝：创作者经济的原点。AI最大的价值是帮我们定义人类是什么。",
    era: "contemporary",
    discipline: "science",
    region: "western",
    tags: ["未来学", "技术哲学", "科技", "创作者经济"],
    works: [],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://en.wikipedia.org/wiki/Kevin_Kelly_(editor)",
    links: [
      { label: "个人官网", url: "https://kk.org", description: "凯文·凯利个人网站与博客" },
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Kevin_Kelly_(editor)", description: "完整的生平与核心思想介绍" },
      { label: "Kelly Society", url: "https://www.kellysociety.org/", description: "凯文·凯利粉丝社群与资料站" },
      { label: "百度百科", url: "https://baike.baidu.com/item/凯文·凯利/6607570", description: "百度百科中文词条" },
    ],
        personalIntroduction: "凯文·凯利是中国科技圈读得最多的外国思想者之一。马化腾和张小龙都公开谈过《失控》对他们的影响。凯利的独特之处在于：他不是预言家，而是率先看到已发生趋势的人。他谈的不是遥远的未来，而是已经到来但未被注意的变化。在通识学习中，他是理解「时代」（Q04）的最佳入口——他帮你在技术变革的浪潮中识别什么是暂时的噪声，什么是不可逆的大势。",
    questionNumbers: [4],
    topicCodes: ["4.1"],
  },
  {
    id: "wp-16",
    slug: "paul-graham",
    name: "保罗·格雷厄姆",
    nameEn: "Paul Graham",
    summary: "程序员、散文家、Y Combinator联合创始人。著有《黑客与画家》，提出「独立思考」「不能说的话」「让身份认同保持小」等影响深远的思想框架。",
    biography: "保罗·格雷厄姆（1964—）是硅谷创业教父，但他首先是一位写作者和思考者。他在个人网站 paulgraham.com 持续写作三十余年，文章以清晰著称。他认为写作就是思考，独立思考是最稀缺的能力之一。",
    coreThoughts: "黑客与画家：编程是一种创造性工作，品味是程序员最重要的能力。不能说的话：每个时代都有思想禁区，最值得思考的话恰恰是那些不能说的。让身份认同保持小：标签越少，思考越自由。独立思考：真正的独立思考是不依赖社会共识的推理能力。",
    era: "contemporary",
    discipline: "science",
    region: "western",
    tags: ["独立思考", "创业", "编程", "写作", "创造力"],
    works: [],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://en.wikipedia.org/wiki/Paul_Graham_(programmer)",
    links: [
      { label: "个人官网", url: "https://paulgraham.com/articles.html", description: "保罗·格雷厄姆全部文章的原创地" },
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Paul_Graham_(programmer)", description: "完整的生平与核心思想介绍" },
      { label: "豆瓣（黑客与画家）", url: "https://book.douban.com/subject/6021440/", description: "豆瓣读书页面" },
    ],
        personalIntroduction: "格雷厄姆可能是所有智者中最好读的一个——他的文章出了名地清晰。但他也是最不好读的一个——他的很多观点会让你不舒服。他说「你不能说的话，往往正是最值得思考的话」；他说「你给自己贴的标签越多，就变得越笨」；他说「大多数人的判断来自社会共识，而不是自己的推理」。这些话说出来让人不舒服，因为你知道它们是真的。在通识学习中，他是「知识的知识」（Q01）的活范本——他不仅谈论独立思考，他的整个职业生涯就是独立思考的实践。",
    questionNumbers: [1],
    topicCodes: ["1.4"],
  },
  {
    id: "wp-17",
    slug: "wang-yangming",
    name: "王阳明",
    nameEn: "Wang Yangming",
    summary: "明代思想家、军事家，心学集大成者。提出「心即理」「知行合一」「致良知」三大命题，将儒学从向外求理转向向内求心，深刻影响了东亚思想史。",
    biography: "王阳明（1472—1529）是中国思想史上少有的将理论与实践统一到极致的人物。他12岁立志「学为圣贤」，34岁在贵州龙场贬谪中悟道，发现「圣人之道，吾性自足」。此后以知行合一为教法，以事上磨练为功夫，以平定宁王之乱显事功，最终以「致良知」完成心学体系。临终遗言「此心光明，亦复何言」，被后世视为儒家理想人格的圆满呈现。",
    coreThoughts: "心即理：理不在外物而在本心，心外无理心外无物。知行合一：知是行的主意，行是知的功夫。致良知：良知人人本具，只是被私欲遮蔽，致良知就是恢复本心的清明。四句教：无善无恶心之体，有善有恶意之动，知善知恶是良知，为善去恶是格物。",
    era: "ancient",
    discipline: "philosophy",
    region: "eastern",
    tags: ["心学", "知行合一", "致良知", "明朝", "宋明理学", "中国哲学"],
    works: [],
    relatedWisePersonSlugs: ["laozi", "zhuangzi"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E7%8E%8B%E9%98%B3%E6%98%8E",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Wang_Yangming", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/wang-yangming/", description: "权威的学术性分析" },
      { label: "Internet Encyclopedia", url: "https://iep.utm.edu/wangyang/", description: "系统的哲学百科条目" },
      { label: "国学网", url: "http://www.guoxue.com/master/wangyangming/wangyangming.htm", description: "王阳明著作全文资料" },
    ],
    personalIntroduction: "王阳明是少数几个「立德、立功、立言」三不朽的人物。你知道他，可能是「知行合一」这四个字。但你可能不知道的是：他不是一个书斋哲学家，他是一个在战场上磨练思想的实践者。他的人生本身就是一个知行合一的实验。在今天，为什么还要读王阳明？因为他解决了一个根本问题：在一个充满不确定性和外部压力的世界里，一个人如何找到内心的确定性。他的答案很简单：回到你的本心。不是逃避外界，而是在与外界互动的过程中磨练内心。",
    questionNumbers: [1],
    topicCodes: ["1.1"],
  },
  {
    id: "wp-18",
    slug: "b-f-skinner",
    name: "斯金纳",
    nameEn: "B.F. Skinner",
    summary: "二十世纪最具争议的心理学家，激进行为主义的捍卫者。提出操作性条件反射理论，发明教学机器，以行为工程改造社会的思想影响了教育学、心理学和当代技术设计。",
    biography: "B.F. 斯金纳（1904—1990）是行为主义心理学最核心的代表人物。他早年梦想成为作家，后在哈佛大学转向心理学，开创了操作性条件反射研究范式。他一生致力于用科学方法理解并改善人类行为——从实验室的老鼠到课堂里的学生，再到整个社会的设计。《瓦尔登第二》描绘的行为工程乌托邦、《超越自由与尊严》对自由意志的否定，使他成为二十世纪最被争议的思想家之一。",
    coreThoughts: "操作性条件反射：行为由其后果改变。激进行为主义：心理学应只关注可观察的行为，而非内在意识。言语行为：语言也是操作性行为。教学机器：将分步强化与即时反馈应用于教育。社会工程设计：应用行为科学改善人类社会。",
    era: "modern",
    discipline: "psychology",
    region: "western",
    tags: ["行为主义", "操作性条件反射", "心理学", "程序教学", "自由意志", "教育技术"],
    works: [],
    relatedWisePersonSlugs: ["sigmuend-freud", "james-march"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E4%BC%AF%E5%B0%94%E8%B5%AB%E6%96%AF%C2%B7%E5%BC%97%E9%9B%B7%E5%BE%B7%E9%87%8C%E5%85%8B%C2%B7%E6%96%AF%E9%87%91%E7%BA%B3",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/B._F._Skinner", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/skinner/", description: "权威的学术性哲学分析" },
      { label: "B.F. Skinner Foundation", url: "https://www.bfskinner.org/", description: "斯金纳基金会官方资料" },
      { label: "APA传记", url: "https://www.apa.org/about/governance/president/bio-bf-skinner", description: "美国心理学会官方传记" },
    ],
    personalIntroduction: "斯金纳的名字在今天常常被简化为'斯金纳箱'和'行为主义'——但你可能不知道的是，他一生真正的动力不是控制人，而是让世界变得更好。他是心理学家中最像工程师的一个，他造装置、造机器、造乌托邦。他的思想在今天比在他那个时代更值得严肃对待——因为你手机里的推荐算法、短视频的刷新机制，本质上都是操作性条件反射的逻辑。他让你思考一个不舒服的问题：如果你的大部分行为都是被环境塑造的，那'自由意志'还剩下多少？",
    questionNumbers: [8],
    topicCodes: ["8.1"],
  },
  {
    id: "wp-19",
    slug: "harold-bloom",
    name: "哈罗德·布鲁姆",
    nameEn: "Harold Bloom",
    summary: "二十世纪最具影响力的文学批评家。提出「影响的焦虑」理论，以《西方正典》捍卫审美批评传统，认为莎士比亚「发明了人性」。",
    biography: "哈罗德·布鲁姆（1930—2019）是二十世纪下半叶最具影响力的文学批评家。他在耶鲁大学任教六十余年，出版了四十多本书。他以《影响的焦虑》颠覆了人们对文学传统的理解——不是传承，而是斗争。他的《西方正典》列出了从但丁到贝克特的26位经典作家，公然反对当时兴起的文化研究潮流。他称政治化的批评方法为「怨恨学派」，坚持文学批评的首要任务是判断审美价值。",
    coreThoughts: "影响的焦虑：后来的诗人通过「创造性误读」前辈来开辟自己的空间。西方正典：文学经典的价值在于「陌生性」——无法被同化的原创力量。审美至上：文学批评的首要任务是判断审美价值，而非揭示政治权力结构。阅读的内在性：阅读不是为了成为好公民，而是为了与自己的内在生命对话。莎士比亚发明了人性：莎士比亚笔下的人物有一种前所未有的「内在性」——他们倾听自己。",
    era: "modern",
    discipline: "literature",
    region: "western",
    tags: ["文学批评", "西方正典", "影响的焦虑", "莎士比亚", "审美批评", "耶鲁学派"],
    works: [],
    relatedWisePersonSlugs: ["cao-xueqin", "sigmuend-freud"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%93%88%E7%BD%97%E5%BE%B7%C2%B7%E5%B8%83%E9%B2%81%E5%A7%86",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Harold_Bloom", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/harold-bloom/", description: "权威的学术性分析" },
      { label: "纽约时报讣告", url: "https://www.nytimes.com/2019/10/14/books/harold-bloom-dead.html", description: "纽约时报讣告" },
      { label: "豆瓣", url: "https://book.douban.com/subject/26868830/", description: "《如何读，为什么读》豆瓣页面" },
    ],
    personalIntroduction: "布鲁姆是那种「没有中间地带」的人。左派觉得他不够进步，右派觉得他不够保守。他说自己只是一个老派的文学批评家——判断好坏，热爱伟大。在今天这个信息过载的时代，他是「什么值得读」的最好的判断者之一。他的书单虽然不完美，但绝对是一个可靠的起点。更重要的是，他提醒你：阅读不是为了升职或考试，而是为了成为一个更宽阔的人。如果你觉得自己被日常琐事淹没了，读一读布鲁姆——他会让你重新记起阅读曾经带给你的那种纯粹的快乐。",
    questionNumbers: [8],
    topicCodes: ["8.5"],
  },
  {
    id: "wp-20",
    slug: "herbert-simon",
    name: "赫伯特·西蒙",
    nameEn: "Herbert A. Simon",
    summary: "二十世纪最罕见的通才，唯一同时获得图灵奖和诺贝尔经济学奖的人。提出有限理性和满意即可原则，开创了认知科学和人工智能的研究范式。",
    biography: "赫伯特·西蒙（1916—2001）是二十世纪最多产的跨学科思想者。他在政治学、经济学、心理学、计算机科学和管理学五个领域做出了奠基性贡献。1947年出版《管理行为》提出组织决策理论，1956年与纽厄尔合作开发了第一个人工智能程序Logic Theorist，1975年获得图灵奖，1978年获得诺贝尔经济学奖。他的有限理性理论颠覆了经济学的完全理性假设，开启了行为经济学和认知科学的新时代。",
    coreThoughts: "有限理性：人只有有限的信息处理能力，不可能做到完全理性。满意即可：决策者通常选择足够好的解而非最优解。信息处理心理学：人类心智是操作符号的信息处理系统。人工科学：凡是人工设计和制造的东西都可以用科学方法研究。组织的决策本质：组织不是权力结构，而是决策过程的分配系统。",
    era: "modern",
    discipline: "social-science",
    region: "western",
    tags: ["有限理性", "满意即可", "认知科学", "人工智能", "组织决策", "行为经济学", "跨学科"],
    works: [],
    relatedWisePersonSlugs: ["james-march", "daniel-kahneman"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%B5%AB%E4%BC%AF%E7%89%B9%C2%B7%E8%A5%BF%E8%92%99",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Herbert_A._Simon", description: "完整的生平与核心思想介绍" },
      { label: "Stanford Encyclopedia", url: "https://plato.stanford.edu/entries/simon-herbert/", description: "权威的学术性哲学分析" },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/economic-sciences/1978/simon/biographical/", description: "诺贝尔奖官方传记" },
      { label: "Turing Award", url: "https://amturing.acm.org/award_winners/simon_1031467.cfm", description: "图灵奖官方介绍" },
    ],
    personalIntroduction: "西蒙是那种你无法用一个标签概括的人。他是经济学家？计算机科学家？心理学家？政治学家？他都会说：不重要——我的问题是关于人类如何决策的，学科标签是别人的事。在今天这个极度专业化的时代，西蒙提醒你：真正重要的不是学科边界，而是问题本身。他的有限理性理论还有一个更个人化的启示：承认自己的有限性不是软弱，而是智慧的开始。如果你觉得必须事事最优才能满意，西蒙告诉你一个更好的策略：找到够好的，然后继续前行。",
    questionNumbers: [8],
    topicCodes: ["8.1"],
  },
  {
    id: "wp-21",
    slug: "george-kelly",
    name: "乔治·凯利",
    nameEn: "George Kelly",
    summary: "个人建构心理学创始人。提出「每个人都是自己的科学家」——人不是被环境决定的，而是被自己对环境的解释决定的，而解释是可以改变的。",
    biography: "乔治·凯利（1905—1967）是美国心理学家，个人建构心理学的创始人。他的核心洞见是：每个人都是科学家——都在建构关于世界的假设，用经验检验它们，根据需要修正它们。他的两卷本巨著《个人建构心理学》（1955）提出了一个完整的人格理论体系，包括建构选择论、角色建构库技术、固定角色疗法。他的理论在生前被主流边缘化，但近年被重新发现——叙事心理学、建构主义疗法、认知行为疗法都深受其影响。",
    coreThoughts: "人是科学家：每个人提出假设检验修正理论，与科学家无本质区别。建构选择论：任何事件都存在不止一种有效解释方式，现实永远可以被重新建构。个人建构系统：人通过一套心智模板（建构）来理解世界——建构越精细灵活，理解越深入。固定角色疗法：行为不是性格的结果，而是改变性格的工具——扮演新角色改变旧建构。",
    era: "modern",
    discipline: "psychology",
    region: "western",
    tags: ["个人建构心理学", "认知建构", "人格理论", "心理治疗", "建构主义", "角色建构库"],
    works: [],
    relatedWisePersonSlugs: ["sigmuend-freud", "b-f-skinner", "herbert-simon"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E4%B9%94%E6%B2%BB%C2%B7%E5%87%AF%E5%88%A9",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/George_Kelly_(psychologist)", description: "完整的生平与核心思想介绍" },
      { label: "个人建构心理学中心", url: "https://www.pcp-net.org/", description: "个人建构心理学国际网站" },
      { label: "RepGrid技术介绍", url: "https://www.repgrid.com/", description: "角色建构库技术详解" },
    ],
    personalIntroduction: "凯利是被低估的心理学大师。他没有弗洛伊德的名气,没有斯金纳的争议——但他可能比两者都对。他说,你不是被你的过去决定的,你是被你的建构系统决定的——而建构系统是可以升级的。这个立场比精神分析更乐观(你不是童年的囚徒),比行为主义更主动(你不是环境的反应器)。如果你觉得被困住了——在亲密关系中重复同样的模式、在工作中遇到同样的问题——凯利会告诉你:你的建构系统需要升级了。不是改变你的处境,而是改变你解释处境的方式。",
    questionNumbers: [8],
    topicCodes: ["8.1"],
  },
  {
    id: "wp-22",
    slug: "steven-pinker",
    name: "史蒂芬·平克",
    nameEn: "Steven Pinker",
    summary: "当代最著名的认知心理学家和公共知识分子之一。提出语言是人类本能，批判白板说，论证人类暴力长期下降，坚定捍卫启蒙理性。",
    biography: "史蒂芬·平克（1954—）是认知心理学家、语言学家、畅销科普作者。他在哈佛获得博士学位，先后在MIT和哈佛任教。他的成名作《语言本能》（1994）将生成语言学和进化心理学以令人惊叹的清晰性带给了大众读者。此后他陆续出版了《心智探奇》《白板》《人性中的善良天使》《当下的启蒙》等重磅著作，成为当代科学写作的代表人物。",
    coreThoughts: "语言本能：语言是人类与生俱来的生物本能，不是文化发明。白板说批判：人类心智不是白纸一张，具有进化塑造的认知结构。暴力下降论：人类暴力在数千年中持续下降。启蒙进步：用数据论证人类在健康、财富、和平、知识等各方面都在进步。理性是真实的：人类能够学会逻辑和科学思维，理性是可测量的能力。",
    era: "contemporary",
    discipline: "psychology",
    region: "western",
    tags: ["认知科学", "进化心理学", "语言本能", "白板", "暴力下降", "启蒙", "理性"],
    works: [],
    relatedWisePersonSlugs: ["noam-chomsky", "daniel-kahneman", "herbert-simon", "b-f-skinner"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%8F%B2%E8%92%82%E8%8A%AC%C2%B7%E5%B9%B3%E5%85%8B",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Steven_Pinker", description: "完整的生平与核心思想介绍" },
      { label: "个人官网", url: "https://stevenpinker.com/", description: "平克个人网站，包含全部著作和文章" },
      { label: "Edge.org", url: "https://www.edge.org/memberbio/steven_pinker", description: "Edge.org个人页面" },
      { label: "Harvard", url: "https://scholar.harvard.edu/pinker/home", description: "哈佛大学个人主页" },
    ],
    personalIntroduction: "平克是当代最会写认知科学的人。你读他的书不会觉得累——他会带你先理解一个观点，给你足够的证据，然后用一个恰到好处的笑话收尾。但不要被他的清晰误导——他触动了这个时代最敏感的神经之一：人性到底是由基因决定的还是由文化塑造的？他的立场（两者都不是，两者都是）让左派和右派都感到不安。如果你觉得世界正在变坏，读一读平克的数据——然后决定你要不要相信他的乐观。",
    questionNumbers: [8],
    topicCodes: ["8.3"],
  },
  {
    id: "wp-23",
    slug: "daniel-kahneman",
    name: "丹尼尔·卡尼曼",
    nameEn: "Daniel Kahneman",
    summary: "心理学史上被引用最多的学者之一，唯一以心理学家身份获得诺贝尔经济学奖的人。提出系统1/系统2思维模型、前景理论和损失厌恶。",
    biography: "丹尼尔·卡尼曼（1934—2024）是行为经济学的奠基人之一。他与阿莫斯·特沃斯基在1970年代的合作被公认是心理学史上最伟大的合作——他们揭示了人类判断中系统性的认知偏差，推翻了经济学中统治半个世纪的期望效用理论。2002年他获得诺贝尔经济学奖。2011年出版的《思考，快与慢》成为全球畅销书，向大众普及了系统1和系统2的概念框架。",
    coreThoughts: "系统1/系统2：系统1是快思考（直觉、自动），系统2是慢思考（分析、控制）——大多数时候是系统1在做主。前景理论：人在不确定下的决策不是按照期望效用，而是受损失厌恶和参照点影响。启发式与偏差：人类使用心理捷径导致系统性判断错误——可得性启发、代表性启发、锚定效应。峰终定律：记忆由最强烈的时刻和结束时刻决定。",
    era: "modern",
    discipline: "psychology",
    region: "western",
    tags: ["行为经济学", "认知心理学", "系统1", "前景理论", "损失厌恶", "启发式与偏差", "诺贝尔奖"],
    works: [],
    relatedWisePersonSlugs: ["herbert-simon", "steven-pinker"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E4%B8%B9%E5%B0%BC%E5%B0%94%C2%B7%E5%8D%A1%E5%B0%BC%E6%9B%BC",
    links: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Daniel_Kahneman", description: "完整的生平与核心思想介绍" },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/economic-sciences/2002/kahneman/biographical/", description: "诺贝尔奖官方传记" },
      { label: "普林斯顿大学", url: "https://scholar.princeton.edu/kahneman/home", description: "普林斯顿大学个人主页" },
    ],
    personalIntroduction: "卡尼曼用一个简单的框架（系统1和系统2）改变了我们对人类思维的理解。他不是一个告诉你「人类很聪明」的人——他告诉你「人类在哪些情况下会犯傻」。但这不是贬低。他揭示的认知偏差每个人都逃不掉，包括他自己在内。他经常说：「我的很多学术判断也是靠系统1做的——区别是我事后会检查。」读卡尼曼最好的理由不是避免犯错——而是对自己犯的错误少一点自责，多一点好奇。",
    questionNumbers: [8],
    topicCodes: ["8.3"],
  },
]

// ========== 问题 ==========
export const mockQuestions: Question[] = [
  {
    id: "q-1",
    code: "Q01",
    number: 1,
    title: "知识的知识",
    subtitle: "所有大问题的前置问题——关于知识本身的知识。认识论、方法论与创新学。",
    summary: "所有大问题的前置问题——关于知识本身的知识。认识论、方法论与创新学。",
    dimension: "meta",
    subTopicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    relatedWisePersonSlugs: ["plato", "aristotle"],
    relatedWorkSlugs: [],
  },
  {
    id: "q-2",
    code: "Q02",
    number: 2,
    title: "如何理解世界",
    subtitle: "世界观——认识我们所处的物质世界与生命世界。",
    summary: "世界观——认识我们所处的物质世界与生命世界。",
    dimension: "heaven",
    subTopicCodes: ["2.1", "2.2", "2.3", "2.4", "2.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-3",
    code: "Q03",
    number: 3,
    title: "如何理解历史",
    subtitle: "从历史中汲取智慧——理解文明的兴衰脉络。",
    summary: "从历史中汲取智慧——理解文明的兴衰脉络。",
    dimension: "heaven",
    subTopicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-4",
    code: "Q04",
    number: 4,
    title: "如何理解时代",
    subtitle: "时代诊断——识别我们所处时代的核心挑战与危机。",
    summary: "时代诊断——识别我们所处时代的核心挑战与危机。",
    dimension: "heaven",
    subTopicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-5",
    code: "Q05",
    number: 5,
    title: "如何理解社会",
    subtitle: "人类社会的基本运作逻辑——交换、交易、博弈与多样性。",
    summary: "人类社会的基本运作逻辑——交换、交易、博弈与多样性。",
    dimension: "earth",
    subTopicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    relatedWisePersonSlugs: ["karl-marx", "max-weber", "adam-smith", "rousseau", "aristotle"],
    relatedWorkSlugs: ["das-kapital", "communist-manifesto", "the-protestant-ethic", "the-wealth-of-nations", "social-contract"],
  },
  {
    id: "q-6",
    code: "Q06",
    number: 6,
    title: "如何理解组织",
    subtitle: "现代社会的组织逻辑——如何创建和管理组织。",
    summary: "现代社会的组织逻辑——如何创建和管理组织。",
    dimension: "earth",
    subTopicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-7",
    code: "Q07",
    number: 7,
    title: "如何理解家庭",
    subtitle: "人生最基本的亲密关系单元——从建立到告别。",
    summary: "人生最基本的亲密关系单元——从建立到告别。",
    dimension: "earth",
    subTopicCodes: ["7.1", "7.2", "7.3", "7.4", "7.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-8",
    code: "Q08",
    number: 8,
    title: "如何理解人性",
    subtitle: "人何以为人——从生理基础到文学表达的人性探索。",
    summary: "人何以为人——从生理基础到文学表达的人性探索。",
    dimension: "human",
    subTopicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-9",
    code: "Q09",
    number: 9,
    title: "如何理解身体",
    subtitle: "身体是灵魂的居所——身心健康与环境适应。",
    summary: "身体是灵魂的居所——身心健康与环境适应。",
    dimension: "human",
    subTopicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-10",
    code: "Q10",
    number: 10,
    title: "如何理解信仰",
    subtitle: "超越性追问——理解不同文明的精神传统。",
    summary: "超越性追问——理解不同文明的精神传统。",
    dimension: "human",
    subTopicCodes: ["10.1", "10.2", "10.3", "10.4", "10.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
]

// ========== 书单 ==========
export const mockBookLists: BookList[] = [
  {
    id: "bl-1",
    slug: "minimum-50",
    title: "最小限度书单",
    summary: "精选 50 本必读经典，覆盖天地人三大维度的通识教育核心书目。",
    description: "这份书单精选了 50 本对人类文明影响最为深远的经典著作，覆盖哲学、科学、文学、社会科学等多个领域，按照「天、地、人」三大维度组织，是构建通识知识体系的最佳起点。",
    type: "minimum",
    bookSlugs: [],
    workSlugs: ["the-republic", "critique-of-pure-reason", "the-origin-of-species", "dream-of-the-red-chamber", "tao-te-ching", "on-the-origin-of-inequality", "das-kapital", "communist-manifesto", "the-protestant-ethic", "the-wealth-of-nations", "social-contract"],
  },
  {
    id: "bl-2",
    slug: "philosophy-starter",
    title: "哲学入门书单",
    summary: "从古希腊到现代哲学，为哲学爱好者准备的入门阅读路径。",
    description: "这份书单为想要了解哲学的读者准备，从古希腊三杰到德国古典哲学，再到现当代哲学，循序渐进地构建哲学知识框架。",
    type: "theme",
    bookSlugs: [],
    workSlugs: ["the-republic", "critique-of-pure-reason"],
  },
  {
    id: "bl-3",
    slug: "science-classics",
    title: "科学经典书单",
    summary: "改变人类科学观念的里程碑式著作。",
    description: "收录了从哥白尼到达尔文，从牛顿到爱因斯坦等科学巨匠的代表作，见证科学观念的变革之路。",
    type: "theme",
    bookSlugs: [],
    workSlugs: ["the-origin-of-species"],
  },
]
