import type { WisePerson, Work, Question, BookList } from "@/types"

// ========== 著作 ==========
export const mockWorks: Work[] = [
  {
    id: "w-1",
    slug: "the-republic",
    title: "理想国",
    authorName: "柏拉图",
    summary: "柏拉图的代表作，以对话体形式探讨正义、理想城邦与哲学王的思想。",
    description: "《理想国》是柏拉图最著名的作品，以苏格拉底为主角的对话体著作。全书共十卷，探讨了正义的本质、理想城邦的构建、哲学王的统治、理念论、教育理论等核心哲学问题。",
    recommendation: "西方哲学的奠基之作，理解柏拉图思想的必读经典。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-2",
    slug: "critique-of-pure-reason",
    title: "纯粹理性批判",
    authorName: "康德",
    summary: "康德的代表作，探讨人类理性的边界与可能性，开创了先验唯心论哲学。",
    description: "《纯粹理性批判》是康德哲学的代表作，也是西方哲学史上最重要的著作之一。书中康德系统地考察了人类理性的能力与界限，提出了「先天综合判断」的概念，试图调和理性主义与经验主义的对立。",
    recommendation: "了解康德哲学乃至整个德国古典哲学的入门钥匙。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-3",
    slug: "the-origin-of-species",
    title: "物种起源",
    authorName: "达尔文",
    summary: "达尔文的划时代著作，提出自然选择理论，改变了人类对生命演化的认知。",
    description: "《物种起源》是达尔文的代表作，书中系统阐述了自然选择理论，论证了物种通过变异和自然选择逐渐演化的过程。这本书彻底改变了人类对生命起源和演化的理解。",
    recommendation: "改变世界科学观的里程碑式著作。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-4",
    slug: "dream-of-the-red-chamber",
    title: "红楼梦",
    authorName: "曹雪芹",
    summary: "中国古典文学的巅峰之作，以贾府的兴衰为背景，展现了封建社会的百态人生。",
    description: "《红楼梦》以贾宝玉、林黛玉、薛宝钗的爱情悲剧为主线，通过对贾、史、王、薛四大家族兴衰的描写，展现了18世纪中国封建社会的广阔画卷。",
    recommendation: "中国文学史上最伟大的小说之一，值得反复品读。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-5",
    slug: "tao-te-ching",
    title: "道德经",
    authorName: "老子",
    summary: "道家思想的根本经典，以简洁深邃的语言探讨「道」与「德」的哲学内涵。",
    description: "《道德经》又称《老子》，是道家哲学最重要的经典。全书仅五千余字，分为八十一章，以精炼的语言阐述了「道」作为宇宙本源和运行规律的哲学思想。",
    recommendation: "中国哲学史上最具影响力的经典之一，字字珠玑。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-6",
    slug: "on-the-origin-of-inequality",
    title: "论人类不平等的起源",
    authorName: "卢梭",
    summary: "卢梭探讨人类社会不平等起源的经典著作，对现代政治哲学影响深远。",
    description: "《论人类不平等的起源》是卢梭应第戎科学院的征文而作。卢梭在书中探讨了人类从自然状态到社会状态的转变过程，以及私有制的产生如何导致了社会不平等。",
    recommendation: "理解社会契约论和现代民主思想的重要基础。",
    genre: "monograph",
    category: "core",
  },
]

// ========== 智者 ==========
export const mockWisePersons: WisePerson[] = [
  {
    id: "wp-1",
    slug: "plato",
    name: "柏拉图",
    nameEn: "Plato",
    summary: "古希腊哲学家，西方哲学奠基人之一，柏拉图学园的创立者。",
    biography: "柏拉图（约公元前427年—前347年）是古希腊最重要的哲学家之一，苏格拉底的学生，亚里士多德的老师。他在雅典创办了柏拉图学园，开创了西方哲学的传统。其哲学体系以「理念论」为核心，认为现实世界是对永恒理念世界的模仿。",
    coreThoughts: "理念论：认为物质世界是流动不居的，而理念世界才是永恒真实的。理想国：提出哲人王统治的理想城邦模型。灵魂不朽说：论证灵魂先于身体存在且在死后继续存在。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "理念论", "理想国"],
    works: [mockWorks[0]],
    relatedWisePersonSlugs: ["aristotle", "socrates"],
  },
  {
    id: "wp-2",
    slug: "immanuel-kant",
    name: "康德",
    nameEn: "Immanuel Kant",
    summary: "德国古典哲学创始人，批判哲学体系的建立者。",
    biography: "伊曼努尔·康德（1724—1804）是德国古典哲学的创始人，也是整个西方哲学史上最重要的哲学家之一。他一生从未离开过哥尼斯堡，但其思想却深刻影响了整个世界。他以三大批判——《纯粹理性批判》《实践理性批判》《判断力批判》——构建了完整的批判哲学体系。",
    coreThoughts: "哥白尼式革命：不是知识必须符合对象，而是对象必须符合我们的认识形式。绝对命令：道德律令是普遍的、必然的，不依赖于任何条件。人为自然立法：知性为自然颁布规律。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["德国古典哲学", "批判哲学", "启蒙运动"],
    works: [mockWorks[1]],
    relatedWisePersonSlugs: ["plato", "rousseau"],
  },
  {
    id: "wp-3",
    slug: "charles-darwin",
    name: "达尔文",
    nameEn: "Charles Darwin",
    summary: "英国博物学家，进化论的奠基人，自然选择理论的提出者。",
    biography: "查尔斯·达尔文（1809—1882）是英国博物学家，进化生物学的奠基人。他随贝格尔号进行了五年的环球考察，收集了大量生物和地质样本。基于这些观察，他提出了以自然选择为核心的进化理论。",
    coreThoughts: "自然选择：物种通过自然选择适应环境，适者生存。共同祖先：所有生命形式来自共同祖先。渐变论：进化是缓慢而渐进的过程。",
    era: "modern",
    discipline: "science",
    region: "western",
    tags: ["进化论", "自然选择", "生物学"],
    works: [mockWorks[2]],
    relatedWisePersonSlugs: [],
  },
  {
    id: "wp-4",
    slug: "cao-xueqin",
    name: "曹雪芹",
    nameEn: "Cao Xueqin",
    summary: "清代文学家，《红楼梦》的作者，中国古典小说的巅峰人物。",
    biography: "曹雪芹（约1715—约1763），名霑，字梦阮，号雪芹。清代著名文学家。他出身于江宁织造世家，幼年家道中落，晚年贫困潦倒。在困顿中创作了《红楼梦》，「批阅十载，增删五次」，留下了这部中国文学史上的不朽巨著。",
    coreThoughts: "现实主义创作：以自家身世为素材，真实再现封建社会的兴衰。人物塑造：塑造了众多性格鲜明的人物形象。悲剧意识：深刻地揭示了封建制度必然崩溃的历史命运。",
    era: "modern",
    discipline: "literature",
    region: "eastern",
    tags: ["中国古典文学", "红楼梦", "现实主义"],
    works: [mockWorks[3]],
    relatedWisePersonSlugs: [],
  },
  {
    id: "wp-5",
    slug: "laozi",
    name: "老子",
    nameEn: "Laozi",
    summary: "中国古代哲学家，道家学派的创始人，《道德经》的作者。",
    biography: "老子（约公元前6世纪），姓李名耳，字聃，春秋末期楚国人。曾任周朝守藏室之史（国家图书馆馆长）。后见周室衰微，西出函谷关，应关令尹喜之请，著《道德经》五千余言，后不知所终。",
    coreThoughts: "道法自然：「道」是宇宙万物的本源和运行规律。无为而治：不妄为，顺应自然规律。对立统一：有无相生，难易相成，福祸相依。",
    era: "ancient",
    discipline: "philosophy",
    region: "eastern",
    tags: ["道家", "无为", "自然"],
    works: [mockWorks[4]],
    relatedWisePersonSlugs: ["zhuangzi"],
  },
  {
    id: "wp-6",
    slug: "rousseau",
    name: "卢梭",
    nameEn: "Jean-Jacques Rousseau",
    summary: "法国启蒙思想家、哲学家，社会契约论的倡导者。",
    biography: "让-雅克·卢梭（1712—1778）是法国启蒙运动的重要思想家。他的政治哲学深刻影响了法国大革命和现代民主思想的发展。卢梭的思想核心是「人生而自由，却无往不在枷锁之中」。",
    coreThoughts: "社会契约论：人们通过社会契约组成共同体，主权在民。自然状态：人类在自然状态中是善良的，文明带来不平等。公意：强调共同体的普遍意志高于个人意志。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["启蒙运动", "社会契约", "民主"],
    works: [mockWorks[5]],
    relatedWisePersonSlugs: ["immanuel-kant"],
  },
  {
    id: "wp-7",
    slug: "aristotle",
    name: "亚里士多德",
    nameEn: "Aristotle",
    summary: "古希腊哲学家，百科全书式的学者，形式逻辑的奠基人。",
    biography: "亚里士多德（公元前384—前322年）是古希腊最博学的哲学家，柏拉图的学生，亚历山大大帝的老师。他在雅典创办了吕克昂学园，其著作涵盖哲学、逻辑学、政治学、物理学、生物学、伦理学等几乎所有学科领域。",
    coreThoughts: "四因说：质料因、形式因、动力因、目的因解释一切事物的存在和变化。中庸之道：美德在于两个极端之间的中道。人是政治动物：人天生是城邦的动物，需要通过政治生活实现幸福。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "逻辑学", "形而上学"],
    works: [],
    relatedWisePersonSlugs: ["plato", "immanuel-kant"],
  },
  {
    id: "wp-8",
    slug: "socrates",
    name: "苏格拉底",
    nameEn: "Socrates",
    summary: "古希腊哲学家，西方哲学的奠基者，以苏格拉底式提问法闻名。",
    biography: "苏格拉底（公元前469—前399年）是古希腊哲学家，西方哲学的奠基人之一。他没有留下任何著作，其思想主要通过学生柏拉图的对话录流传后世。他通过不断追问的方式引导人们反思自己的知识和信念，这种方法被称为「苏格拉底式反诘法」。",
    coreThoughts: "认识你自己：哲学的首要任务是认识自我。精神助产术：通过提问帮助他人产生知识。美德即知识：真正的美德基于对善的知识。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "辩证法", "伦理"],
    works: [],
    relatedWisePersonSlugs: ["plato", "aristotle"],
  },
  {
    id: "wp-9",
    slug: "zhuangzi",
    name: "庄子",
    nameEn: "Zhuangzi",
    summary: "中国古代哲学家，道家思想的重要代表人物。",
    biography: "庄子（约公元前369—前286年），名周，战国时期宋国蒙人。他是继老子之后道家思想最重要的代表人物，与老子并称「老庄」。庄子的文章想象丰富，文笔汪洋恣肆，以寓言故事的形式阐述深刻的哲学思想。",
    coreThoughts: "齐物论：万物在道的层面上是齐一的，没有是非、善恶的绝对区别。逍遥游：追求精神的绝对自由和超越。无用之用：看似无用的东西往往有更大的用途。",
    era: "ancient",
    discipline: "philosophy",
    region: "eastern",
    tags: ["道家", "逍遥", "齐物"],
    works: [],
    relatedWisePersonSlugs: ["laozi"],
  },
  {
    id: "wp-10",
    slug: "sigmuend-freud",
    name: "弗洛伊德",
    nameEn: "Sigmund Freud",
    summary: "奥地利心理学家，精神分析学派的创始人。",
    biography: "西格蒙德·弗洛伊德（1856—1939）是奥地利心理学家，精神分析学派的创始人。他提出的潜意识理论、人格结构理论（本我、自我、超我）和性心理发展理论，深刻影响了20世纪的心理学、文学、艺术和社会思想。",
    coreThoughts: "潜意识：人的心理活动大部分在潜意识层面进行，影响着我们的行为。人格结构：本我遵循快乐原则，自我遵循现实原则，超我遵循道德原则。梦的解析：梦是愿望的满足，是通往潜意识的皇家大道。",
    era: "modern",
    discipline: "psychology",
    region: "western",
    tags: ["精神分析", "潜意识", "心理学"],
    works: [],
    relatedWisePersonSlugs: [],
  },
]

// ========== 问题 ==========
export const mockQuestions: Question[] = [
  {
    id: "q-1",
    code: "Q01",
    number: 1,
    title: "知识的知识",
    subtitle: "所有大问题的前置问题——关于知识本身的知识。认识论、方法论与创新学。",
    summary: "所有大问题的前置问题——关于知识本身的知识。认识论、方法论与创新学。",
    dimension: "heaven",
    subTopicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    relatedWisePersonSlugs: ["plato", "aristotle"],
    relatedWorkSlugs: [],
  },
  {
    id: "q-2",
    code: "Q02",
    number: 2,
    title: "如何理解世界",
    subtitle: "世界观——认识我们所处的物质世界与生命世界。",
    summary: "世界观——认识我们所处的物质世界与生命世界。",
    dimension: "heaven",
    subTopicCodes: ["2.1", "2.2", "2.3", "2.4", "2.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-3",
    code: "Q03",
    number: 3,
    title: "如何理解历史",
    subtitle: "从历史中汲取智慧——理解文明的兴衰脉络。",
    summary: "从历史中汲取智慧——理解文明的兴衰脉络。",
    dimension: "heaven",
    subTopicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-4",
    code: "Q04",
    number: 4,
    title: "如何理解时代",
    subtitle: "时代诊断——识别我们所处时代的核心挑战与危机。",
    summary: "时代诊断——识别我们所处时代的核心挑战与危机。",
    dimension: "earth",
    subTopicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-5",
    code: "Q05",
    number: 5,
    title: "如何理解社会",
    subtitle: "人类社会的基本运作逻辑——交换、交易、博弈与多样性。",
    summary: "人类社会的基本运作逻辑——交换、交易、博弈与多样性。",
    dimension: "earth",
    subTopicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-6",
    code: "Q06",
    number: 6,
    title: "如何理解组织",
    subtitle: "现代社会的组织逻辑——如何创建和管理组织。",
    summary: "现代社会的组织逻辑——如何创建和管理组织。",
    dimension: "earth",
    subTopicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-7",
    code: "Q07",
    number: 7,
    title: "如何理解家庭",
    subtitle: "人生最基本的亲密关系单元——从建立到告别。",
    summary: "人生最基本的亲密关系单元——从建立到告别。",
    dimension: "earth",
    subTopicCodes: ["7.1", "7.2", "7.3", "7.4", "7.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-8",
    code: "Q08",
    number: 8,
    title: "如何理解人性",
    subtitle: "人何以为人——从生理基础到文学表达的人性探索。",
    summary: "人何以为人——从生理基础到文学表达的人性探索。",
    dimension: "human",
    subTopicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-9",
    code: "Q09",
    number: 9,
    title: "如何理解身体",
    subtitle: "身体是灵魂的居所——身心健康与环境适应。",
    summary: "身体是灵魂的居所——身心健康与环境适应。",
    dimension: "human",
    subTopicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-10",
    code: "Q10",
    number: 10,
    title: "如何理解信仰",
    subtitle: "超越性追问——理解不同文明的精神传统。",
    summary: "超越性追问——理解不同文明的精神传统。",
    dimension: "human",
    subTopicCodes: ["10.1", "10.2", "10.3", "10.4", "10.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
]

// ========== 书单 ==========
export const mockBookLists: BookList[] = [
  {
    id: "bl-1",
    slug: "minimum-50",
    title: "最小限度书单",
    summary: "精选 50 本必读经典，覆盖天地人三大维度的通识教育核心书目。",
    description: "这份书单精选了 50 本对人类文明影响最为深远的经典著作，覆盖哲学、科学、文学、社会科学等多个领域，按照「天、地、人」三大维度组织，是构建通识知识体系的最佳起点。",
    type: "minimum",
    bookSlugs: [],
    workSlugs: ["the-republic", "critique-of-pure-reason", "the-origin-of-species", "dream-of-the-red-chamber", "tao-te-ching", "on-the-origin-of-inequality"],
  },
  {
    id: "bl-2",
    slug: "philosophy-starter",
    title: "哲学入门书单",
    summary: "从古希腊到现代哲学，为哲学爱好者准备的入门阅读路径。",
    description: "这份书单为想要了解哲学的读者准备，从古希腊三杰到德国古典哲学，再到现当代哲学，循序渐进地构建哲学知识框架。",
    type: "theme",
    bookSlugs: [],
    workSlugs: ["the-republic", "critique-of-pure-reason"],
  },
  {
    id: "bl-3",
    slug: "science-classics",
    title: "科学经典书单",
    summary: "改变人类科学观念的里程碑式著作。",
    description: "收录了从哥白尼到达尔文，从牛顿到爱因斯坦等科学巨匠的代表作，见证科学观念的变革之路。",
    type: "theme",
    bookSlugs: [],
    workSlugs: ["the-origin-of-species"],
  },
]
