import type { WisePerson, Work, Question, BookList } from "@/types"

// ========== 著作 ==========
export const mockWorks: Work[] = [
  {
    id: "w-1",
    slug: "the-republic",
    title: "理想国",
    authorName: "柏拉图",
    summary: "柏拉图的代表作，以对话体形式探讨正义、理想城邦与哲学王的思想。",
    description: "《理想国》是柏拉图最著名的作品，以苏格拉底为主角的对话体著作。全书共十卷，探讨了正义的本质、理想城邦的构建、哲学王的统治、理念论、教育理论等核心哲学问题。",
    recommendation: "西方哲学的奠基之作，理解柏拉图思想的必读经典。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-7",
    slug: "das-kapital",
    title: "资本论",
    authorName: "马克思",
    summary: "马克思的代表作，系统阐述了剩余价值理论和资本主义经济危机理论。",
    description: "《资本论》是马克思的代表作，第一卷于1867年出版。书中系统阐述了剩余价值理论，揭示了资本主义剥削的秘密，论证了资本主义经济危机的必然性。",
    recommendation: "理解马克思主义经济学的核心著作。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-8",
    slug: "communist-manifesto",
    title: "共产党宣言",
    authorName: "马克思、恩格斯",
    summary: "马克思主义的纲领性文件，阐述了阶级斗争理论和共产主义理想。",
    description: "《共产党宣言》是马克思和恩格斯合著的著作，发表于1848年。书中阐述了历史唯物主义的基本原理，提出了阶级斗争理论，号召「全世界无产者，联合起来！」",
    recommendation: "理解马克思主义的入门读物。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-9",
    slug: "the-protestant-ethic",
    title: "新教伦理与资本主义精神",
    authorName: "马克斯·韦伯",
    summary: "韦伯的代表作，探讨新教伦理如何促进了资本主义精神的兴起。",
    description: "《新教伦理与资本主义精神》是马克斯·韦伯的代表作，发表于1904-1905年。韦伯在书中论证：加尔文主义的「天职」观念和入世禁欲主义，为资本主义精神的兴起提供了伦理基础。",
    recommendation: "理解文化因素如何影响经济发展的经典著作。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-10",
    slug: "the-wealth-of-nations",
    title: "国富论",
    authorName: "亚当·斯密",
    summary: "亚当·斯密的代表作，古典经济学的奠基之作。",
    description: "《国富论》全名《国民财富的性质和原因的研究》，是亚当·斯密的代表作，发表于1776年。书中系统阐述了劳动价值论、分工理论和自由市场经济的重要性。",
    recommendation: "理解古典经济学的必读经典。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-11",
    slug: "social-contract",
    title: "社会契约论",
    authorName: "卢梭",
    summary: "卢梭的代表作，阐述社会契约理论和人民主权思想。",
    description: "《社会契约论》是卢梭的代表作，发表于1762年。书中提出了「公意」理论和「人生而自由，却无往不在枷锁之中」的著名论断，深刻影响了现代民主思想。",
    recommendation: "理解现代政治哲学的必读经典。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-2",
    slug: "critique-of-pure-reason",
    title: "纯粹理性批判",
    authorName: "康德",
    summary: "康德的代表作，探讨人类理性的边界与可能性，开创了先验唯心论哲学。",
    description: "《纯粹理性批判》是康德哲学的代表作，也是西方哲学史上最重要的著作之一。书中康德系统地考察了人类理性的能力与界限，提出了「先天综合判断」的概念，试图调和理性主义与经验主义的对立。",
    recommendation: "了解康德哲学乃至整个德国古典哲学的入门钥匙。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-3",
    slug: "the-origin-of-species",
    title: "物种起源",
    authorName: "达尔文",
    summary: "达尔文的划时代著作，提出自然选择理论，改变了人类对生命演化的认知。",
    description: "《物种起源》是达尔文的代表作，书中系统阐述了自然选择理论，论证了物种通过变异和自然选择逐渐演化的过程。这本书彻底改变了人类对生命起源和演化的理解。",
    recommendation: "改变世界科学观的里程碑式著作。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-4",
    slug: "dream-of-the-red-chamber",
    title: "红楼梦",
    authorName: "曹雪芹",
    summary: "中国古典文学的巅峰之作，以贾府的兴衰为背景，展现了封建社会的百态人生。",
    description: "《红楼梦》以贾宝玉、林黛玉、薛宝钗的爱情悲剧为主线，通过对贾、史、王、薛四大家族兴衰的描写，展现了18世纪中国封建社会的广阔画卷。",
    recommendation: "中国文学史上最伟大的小说之一，值得反复品读。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-5",
    slug: "tao-te-ching",
    title: "道德经",
    authorName: "老子",
    summary: "道家思想的根本经典，以简洁深邃的语言探讨「道」与「德」的哲学内涵。",
    description: "《道德经》又称《老子》，是道家哲学最重要的经典。全书仅五千余字，分为八十一章，以精炼的语言阐述了「道」作为宇宙本源和运行规律的哲学思想。",
    recommendation: "中国哲学史上最具影响力的经典之一，字字珠玑。",
    genre: "monograph",
    category: "core",
  },
  {
    id: "w-6",
    slug: "on-the-origin-of-inequality",
    title: "论人类不平等的起源",
    authorName: "卢梭",
    summary: "卢梭探讨人类社会不平等起源的经典著作，对现代政治哲学影响深远。",
    description: "《论人类不平等的起源》是卢梭应第戎科学院的征文而作。卢梭在书中探讨了人类从自然状态到社会状态的转变过程，以及私有制的产生如何导致了社会不平等。",
    recommendation: "理解社会契约论和现代民主思想的重要基础。",
    genre: "monograph",
    category: "core",
  },
]

// ========== 智者 ==========
export const mockWisePersons: WisePerson[] = [
  {
    id: "wp-1",
    slug: "plato",
    name: "柏拉图",
    nameEn: "Plato",
    summary: "古希腊哲学家，雅典人，其著作大多以对话录形式纪录，并创办了著名的柏拉图学院。柏拉图是苏格拉底的学生，亚里士多德的老师，他们三人被普遍认为是西方哲学的奠基人，史称「希腊三哲」。",
    biography: "柏拉图（约公元前427年—前347年）是古希腊最重要的哲学家之一，苏格拉底的学生，亚里士多德的老师。他在雅典创办了柏拉图学园，开创了西方哲学的传统。其哲学体系以「理念论」为核心，认为现实世界是对永恒理念世界的模仿。",
    coreThoughts: "理念论：认为物质世界是流动不居的，而理念世界才是永恒真实的。理想国：提出哲人王统治的理想城邦模型。灵魂不朽说：论证灵魂先于身体存在且在死后继续存在。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "理念论", "理想国"],
    works: [mockWorks[0]],
    relatedWisePersonSlugs: ["aristotle", "socrates"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E6%9F%8F%E6%8B%89%E5%9B%BE",
    personalIntroduction: "柏拉图是西方哲学史上第一位建立完整体系的 thinker，其「理念论」认为我们感知的物质世界只是永恒理念世界的投影。这一思想深刻影响了后世两千多年的哲学走向，也为我们理解「知识的知识」（Q01）提供了最原初的框架：知识与真理的最终对象不是流变的现象，而是不变的理型。在通识学习中，柏拉图提醒我们——在具体学科知识之外，存在着更为根本的关于「什么是真实」「什么是正义」「什么是美好」的追问。他的《理想国》不仅是一本政治哲学著作，更是一张引导人从洞穴走向光明的教育地图。",
    questionNumbers: [1],
    topicCodes: ["1.1"],
  },
  {
    id: "wp-2",
    slug: "immanuel-kant",
    name: "康德",
    nameEn: "Immanuel Kant",
    summary: "启蒙时代德意志哲学家，德国古典哲学创始人。其学说影响近代西方哲学，开创了德国唯心主义和康德义务主义等流派。他调和了笛卡儿的理性主义与培根的经验主义，被视为继苏格拉底、柏拉图和亚里士多德之后西方最具影响力的思想家之一。",
    biography: "伊曼努尔·康德（1724—1804）是德国古典哲学的创始人，也是整个西方哲学史上最重要的哲学家之一。他一生从未离开过哥尼斯堡，但其思想却深刻影响了整个世界。他以三大批判——《纯粹理性批判》《实践理性批判》《判断力批判》——构建了完整的批判哲学体系。",
    coreThoughts: "哥白尼式革命：不是知识必须符合对象，而是对象必须符合我们的认识形式。绝对命令：道德律令是普遍的、必然的，不依赖于任何条件。人为自然立法：知性为自然颁布规律。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["德国古典哲学", "批判哲学", "启蒙运动"],
    works: [mockWorks[1]],
    relatedWisePersonSlugs: ["plato", "rousseau"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%BA%B7%E5%BE%B7",
    personalIntroduction: "康德在哲学史上完成了一次「哥白尼式革命」——不是知识必须符合对象，而是对象必须符合我们的认识形式。这一洞见彻底改变了我们对人类理性边界的理解，也为「知识的知识」（Q01）提供了认识论的基石。康德的三大批判构建了一套完整的哲学体系：我们如何知道（纯粹理性批判）、我们应当如何行动（实践理性批判）、以及我们如何感受美与目的（判断力批判）。在通识学习中，康德是一座绕不开的山峰——他教会我们以批判性思维审视一切知识的边界与条件，在理性与信仰之间划定清晰的界限。",
    questionNumbers: [1],
    topicCodes: ["1.1"],
  },
  {
    id: "wp-3",
    slug: "charles-darwin",
    name: "达尔文",
    nameEn: "Charles Darwin",
    summary: "英国博物学家、地质学家和生物学家，最著名的贡献是自然选择演化理论。他认为所有物种都是从少数共同祖先演化而来的，其理论成为演化机制的主要解释，奠定了现代演化思想的基础，被誉为「现今生物学的基石」。",
    biography: "查尔斯·达尔文（1809—1882）是英国博物学家，进化生物学的奠基人。他随贝格尔号进行了五年的环球考察，收集了大量生物和地质样本。基于这些观察，他提出了以自然选择为核心的进化理论。",
    coreThoughts: "自然选择：物种通过自然选择适应环境，适者生存。共同祖先：所有生命形式来自共同祖先。渐变论：进化是缓慢而渐进的过程。",
    era: "modern",
    discipline: "science",
    region: "western",
    tags: ["进化论", "自然选择", "生物学"],
    works: [mockWorks[2]],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%BE%BE%E5%B0%94%E6%96%87",
    personalIntroduction: "达尔文的进化论不只是生物学的一个分支理论，它是一场世界观的革命。在达尔文之前，人们相信物种是独立创造、永恒不变的；达尔文之后，我们认识到所有生命——包括人类——都来自共同的祖先，通过自然选择在漫长的岁月中演化而来。这一思想深刻影响了「如何理解世界」（Q02）这一根本问题：世界不是静止的、被设计的，而是动态的、演化的。达尔文教会我们以演化的眼光看待一切——从生物到社会、从文化到思想，变化与适应才是永恒的常态。在通识教育的框架中，演化思维是一种跨学科的认知工具。",
    questionNumbers: [2],
    topicCodes: ["2.2"],
  },
  {
    id: "wp-4",
    slug: "cao-xueqin",
    name: "曹雪芹",
    nameEn: "Cao Xueqin",
    summary: "清朝小说家、诗人、画家，中国古典名著《红楼梦》的作者。生于江宁府（今南京），祖籍辽阳，清内务府正白旗包衣世家出身。",
    biography: "曹雪芹（约1715—约1763），名霑，字梦阮，号雪芹。清代著名文学家。他出身于江宁织造世家，幼年家道中落，晚年贫困潦倒。在困顿中创作了《红楼梦》，「批阅十载，增删五次」，留下了这部中国文学史上的不朽巨著。",
    coreThoughts: "现实主义创作：以自家身世为素材，真实再现封建社会的兴衰。人物塑造：塑造了众多性格鲜明的人物形象。悲剧意识：深刻地揭示了封建制度必然崩溃的历史命运。",
    era: "modern",
    discipline: "literature",
    region: "eastern",
    tags: ["中国古典文学", "红楼梦", "现实主义"],
    works: [mockWorks[3]],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E6%9B%B9%E9%9B%AA%E8%8A%B9",
    personalIntroduction: "曹雪芹的《红楼梦》是中国文学史上最伟大的作品之一，它不仅是一部小说，更是一部关于人性的百科全书。在「如何理解人性」（Q08）这一维度上，曹雪芹以惊人的深度刻画了人物的复杂性与命运的无常。他笔下的贾宝玉、林黛玉、薛宝钗等人物不再是善恶分明的类型，而是充满矛盾与困惑的真实个体。曹雪芹教会我们：理解人性需要同情心而非道德审判，需要洞察力而非简单归类。在通识学习的语境中，《红楼梦》是一座关于「人如何活着、如何爱着、如何失去」的文学丰碑。",
    questionNumbers: [8],
    topicCodes: ["8.5"],
  },
  {
    id: "wp-5",
    slug: "laozi",
    name: "老子",
    nameEn: "Laozi",
    summary: "中国春秋时代思想家，道家学派创始人。姓李名耳，字聃，曾担任周朝守藏室之史。其所著《老子》（又称《道德经》）是道家哲学的根本经典，被奉为道教最重要经典之一。",
    biography: "老子（约公元前6世纪），姓李名耳，字聃，春秋末期楚国人。曾任周朝守藏室之史（国家图书馆馆长）。后见周室衰微，西出函谷关，应关令尹喜之请，著《道德经》五千余言，后不知所终。",
    coreThoughts: "道法自然：「道」是宇宙万物的本源和运行规律。无为而治：不妄为，顺应自然规律。对立统一：有无相生，难易相成，福祸相依。",
    era: "ancient",
    discipline: "philosophy",
    region: "eastern",
    tags: ["道家", "无为", "自然"],
    works: [mockWorks[4]],
    relatedWisePersonSlugs: ["zhuangzi"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%80%81%E5%AD%90",
    personalIntroduction: "老子是中国哲学史上最深邃的 thinker 之一，五千言的《道德经》以极简的语言触及了宇宙、人生与社会的根本问题。「道可道，非常道」——真正的智慧不可言说，却可以通过体悟来把握。老子的思想在通识教育中具有独特的价值：他提出的「无为而治」不是消极不作为，而是要求我们理解事物的自然规律，顺势而为而不妄为。在「知识的知识」（Q01）层面，老子提醒我们：最高明的认知不是积累信息，而是回归本源，理解大道运行的规律。他的对立统一思维——有无相生、难易相成——为后世提供了深刻的辩证智慧。",
    questionNumbers: [1,10],
    topicCodes: ["1.1", "10.3"],
  },
  {
    id: "wp-6",
    slug: "rousseau",
    name: "卢梭",
    nameEn: "Jean-Jacques Rousseau",
    summary: "启蒙时代法国哲学家、政治学家、教育学家、作曲家与浪漫主义文学家。其《论人类不平等的起源与基础》深刻地影响了西方哲学的发展；代表作《社会契约论》中所论述的人民主权及民主政治哲学思想，深远影响了启蒙运动、法国大革命以至现代政治与教育思想。",
    biography: "让-雅克·卢梭（1712—1778）是法国启蒙运动的重要思想家。他的政治哲学深刻影响了法国大革命和现代民主思想的发展。卢梭的思想核心是「人生而自由，却无往不在枷锁之中」。",
    coreThoughts: "社会契约论：人们通过社会契约组成共同体，主权在民。自然状态：人类在自然状态中是善良的，文明带来不平等。公意：强调共同体的普遍意志高于个人意志。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["启蒙运动", "社会契约", "民主"],
    works: [mockWorks[5], mockWorks[10]],
    relatedWisePersonSlugs: ["immanuel-kant"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%AE%A9-%E9%9B%85%E5%85%8B%C2%B7%E5%8D%A2%E6%A2%AD",
    personalIntroduction: "卢梭是启蒙运动中最具原创性的思想家之一，他对「如何理解社会」（Q05）这一问题的思考至今仍具有震撼力。《论人类不平等的起源》揭示了一个深刻的悖论：文明带来了进步，却也制造了不平等；社会契约应当保障自由，现实中却往往成为枷锁。卢梭的「人生而自由，却无往不在枷锁之中」是对现代人处境最精准的概括之一。在通识学习中，卢梭教会我们以批判的眼光审视社会制度——不把既有秩序当作理所当然，而是追问其合法性与正当性。他的思想是理解现代政治哲学不可绕过的起点。",
    questionNumbers: [5],
    topicCodes: ["5.4"],
  },
  {
    id: "wp-11",
    slug: "karl-marx",
    name: "卡尔·马克思",
    nameEn: "Karl Marx",
    summary: "德国哲学家、经济学家、革命家，马克思主义的创始人。其思想对20世纪的社会运动产生了深远影响。",
    biography: "卡尔·马克思（1818—1883）是德国哲学家、经济学家、革命家，马克思主义的创始人。他与恩格斯合著的《共产党宣言》和《资本论》深刻影响了20世纪的社会运动。",
    coreThoughts: "历史唯物主义：不是意识决定存在，而是社会存在决定意识。阶级斗争：至今一切社会的历史都是阶级斗争的历史。剩余价值：利润来自工人的剩余劳动。",
    era: "modern",
    discipline: "philosophy",
    region: "western",
    tags: ["马克思主义", "阶级斗争", "剩余价值"],
    works: [mockWorks[6], mockWorks[7]],
    relatedWisePersonSlugs: ["max-weber", "adam-smith"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%8D%A1%E5%B0%94%C2%B7%E9%A9%AC%E5%85%8B%E6%80%9D",
    personalIntroduction: "马克思是历史上最有影响力的思想家之一。他的阶级斗争理论和历史唯物主义彻底改变了我们理解社会的方式。在「如何理解社会」（Q05）这一维度，马克思提供了最犀利的分析工具：社会不是和谐的有机体，而是阶级斗争的战场；历史不是杂乱无章的事件串，而是生产方式演化的结果。",
    questionNumbers: [5],
    topicCodes: ["5.1"],
  },
  {
    id: "wp-12",
    slug: "max-weber",
    name: "马克斯·韦伯",
    nameEn: "Max Weber",
    summary: "德国社会学家、哲学家、政治经济学家，社会学三大奠基人之一。以《新教伦理与资本主义精神》闻名。",
    biography: "马克斯·韦伯（1864—1920）是德国社会学家、哲学家、政治经济学家，社会学三大奠基人之一。他的《新教伦理与资本主义精神》探讨了文化因素（特别是宗教）如何塑造经济现实。",
    coreThoughts: "理性化：现代社会的核心趋势，用计算取代传统。新教伦理：新教伦理促进了资本主义精神的兴起。理想类型：社会科学的研究方法。科层制：现代组织的必然命运。",
    era: "modern",
    discipline: "sociology",
    region: "western",
    tags: ["社会学", "理性化", "新教伦理"],
    works: [mockWorks[8]],
    relatedWisePersonSlugs: ["karl-marx"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E9%A9%AC%E5%85%8B%E6%96%AF%C2%B7%E9%9F%81%E4%BC%AF",
    personalIntroduction: "韦伯是社会学三大奠基人之一（与马克思、涂尔干并列）。他在「如何理解社会」（Q05）维度上的独特贡献在于：他既看到经济因素的重要性，也强调文化、宗教、观念的独立作用。《新教伦理与资本主义精神》展示了观念如何塑造经济现实，这对我们理解不同文明的差异具有重要意义。",
    questionNumbers: [5],
    topicCodes: ["5.1"],
  },
  {
    id: "wp-13",
    slug: "adam-smith",
    name: "亚当·斯密",
    nameEn: "Adam Smith",
    summary: "苏格兰哲学家、经济学家，古典经济学创始人。以《国富论》《道德情操论》闻名。",
    biography: "亚当·斯密（1723—1790）是苏格兰哲学家、经济学家，古典经济学的创始人。他的《国富论》奠定了现代经济学的基础，《道德情操论》则探讨了人类道德判断的来源。",
    coreThoughts: "看不见的手：市场机制协调自利行为。同情心：人类有天然的同情能力。分工：提高生产力的关键。",
    era: "modern",
    discipline: "economics",
    region: "western",
    tags: ["古典经济学", "看不见的手", "同情心"],
    works: [mockWorks[9]],
    relatedWisePersonSlugs: ["karl-marx"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E4%BA%9A%E5%BD%93%C2%B7%E6%96%AF%E5%AF%86%E6%96%AF",
    personalIntroduction: "亚当·斯密是古典经济学的创始人，但他也是道德哲学家。《国富论》中的「看不见的手」理论和《道德情操论》中的「同情心」理论共同构成了他对人性的完整理解。在「如何理解社会」（Q05）中，斯密提供了理解市场经济的基础：自利行为如何通过市场机制产生社会福利？市场经济需要什么道德基础？",
    questionNumbers: [5],
    topicCodes: ["5.2"],
  },
  {
    id: "wp-7",
    slug: "aristotle",
    name: "亚里士多德",
    nameEn: "Aristotle",
    summary: "古希腊哲学家，柏拉图的学生、亚历山大大帝的老师。他与柏拉图、苏格拉底并称西方哲学的奠基者，其著作构成了西方哲学最早的系统，涵盖道德、美学、逻辑、科学、政治及形而上学等领域，被誉为百科全书式的学者。",
    biography: "亚里士多德（公元前384—前322年）是古希腊最博学的哲学家，柏拉图的学生，亚历山大大帝的老师。他在雅典创办了吕克昂学园，其著作涵盖哲学、逻辑学、政治学、物理学、生物学、伦理学等几乎所有学科领域。",
    coreThoughts: "四因说：质料因、形式因、动力因、目的因解释一切事物的存在和变化。中庸之道：美德在于两个极端之间的中道。人是政治动物：人天生是城邦的动物，需要通过政治生活实现幸福。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "逻辑学", "形而上学"],
    works: [],
    relatedWisePersonSlugs: ["plato", "immanuel-kant"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E4%BA%9A%E9%87%8C%E5%A3%AB%E5%A4%9A%E5%BE%B7",
    personalIntroduction: "亚里士多德是西方第一位百科全书式的学者，他几乎凭一己之力为后世西方知识体系奠定了基础。从逻辑学到物理学、从伦理学到政治学、从生物学到诗学——他的研究覆盖了人类知识的全部疆域。在通识教育的语境下，亚里士多德最重要的遗产是他的分类思维和因果分析方法：「四因说」提供了一个理解万物的通用框架——追问事物的质料、形式、动力和目的。他还提出了「人是政治动物」的命题，提醒我们：理解社会与组织（Q05、Q06）不能脱离人的天性。亚里士多德教会我们以系统化的方式思考世界——不是零散地获取知识，而是建立有机的知识结构。",
    questionNumbers: [1, 5],
    topicCodes: ["1.1", "5.1"],
  },
  {
    id: "wp-8",
    slug: "socrates",
    name: "苏格拉底",
    nameEn: "Socrates",
    summary: "古希腊哲学家，与柏拉图、亚里士多德并称「希腊三贤」。他未留下任何著作，其思想主要通过学生柏拉图的对话录流传后世。他以苏格拉底式反诘法引导人们反思知识与信念，被公认为西方哲学的奠基者之一。",
    biography: "苏格拉底（公元前469—前399年）是古希腊哲学家，西方哲学的奠基人之一。他没有留下任何著作，其思想主要通过学生柏拉图的对话录流传后世。他通过不断追问的方式引导人们反思自己的知识和信念，这种方法被称为「苏格拉底式反诘法」。",
    coreThoughts: "认识你自己：哲学的首要任务是认识自我。精神助产术：通过提问帮助他人产生知识。美德即知识：真正的美德基于对善的知识。",
    era: "ancient",
    discipline: "philosophy",
    region: "western",
    tags: ["古希腊哲学", "辩证法", "伦理"],
    works: [],
    relatedWisePersonSlugs: ["plato", "aristotle"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%8B%8F%E6%A0%BC%E6%8B%89%E5%BA%95",
    personalIntroduction: "苏格拉底没有留下任何著作，却成为西方哲学最伟大的奠基人之一。他的方法——通过不断追问来暴露人们知识中的矛盾与盲区——被后世称为「苏格拉底式反诘法」。这种方法本身就是一种关于「知识的知识」（Q01）的实践：真正的智慧不是拥有答案，而是承认自己的无知。苏格拉底的「认识你自己」是哲学史上最深刻也最简洁的箴言。在通识学习中，苏格拉底精神意味着不盲从权威、不满足于表面答案、持续地质疑与反思。他的死——为捍卫独立思考而饮下毒酒——是对哲学精神最庄严的诠释。",
    questionNumbers: [1],
    topicCodes: ["1.1"],
  },
  {
    id: "wp-9",
    slug: "zhuangzi",
    name: "庄子",
    nameEn: "Zhuangzi",
    summary: "战国时期道家代表人物，继承并发展了老子思想，后世并称「老庄」。其著作《庄子》被尊为《南华经》。庄子文章想象丰富，以寓言故事阐述深刻的哲学思想。",
    biography: "庄子（约公元前369—前286年），名周，战国时期宋国蒙人。他是继老子之后道家思想最重要的代表人物，与老子并称「老庄」。庄子的文章想象丰富，文笔汪洋恣肆，以寓言故事的形式阐述深刻的哲学思想。",
    coreThoughts: "齐物论：万物在道的层面上是齐一的，没有是非、善恶的绝对区别。逍遥游：追求精神的绝对自由和超越。无用之用：看似无用的东西往往有更大的用途。",
    era: "ancient",
    discipline: "philosophy",
    region: "eastern",
    tags: ["道家", "逍遥", "齐物"],
    works: [],
    relatedWisePersonSlugs: ["laozi"],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E5%BA%84%E5%AD%90",
    personalIntroduction: "庄子是继老子之后道家思想最伟大的代表，他以汪洋恣肆的想象力和深刻的哲学洞见，将道家思想推向了新的高度。在通识学习的语境中，庄子的价值在于他提供了一种超越世俗认知框架的思维方式：「齐物论」消解了是非对错的绝对界限，教会我们以更开阔的视野看待分歧；「逍遥游」则勾勒了一种精神绝对自由的理想状态。庄子的「无用之用」是对功利主义思维最深刻的批判——那些看似无用的东西，往往有不可替代的价值。在十问框架中，庄子帮助我们反思「知识的知识」（Q01）的另一面：有些真理不在逻辑推演中，而在直觉与体悟之中。",
    questionNumbers: [1,10],
    topicCodes: ["1.1", "10.3"],
  },
  {
    id: "wp-10",
    slug: "sigmuend-freud",
    name: "弗洛伊德",
    nameEn: "Sigmund Freud",
    summary: "奥地利心理学家、精神分析学创始人、哲学家。精神分析学是一种通过医患对话评估和治疗心理冲突的临床方法，他提出的潜意识理论、人格结构理论深刻影响了20世纪的心理学、文学、艺术和社会思想，被公认为20世纪最具影响力的思想家之一。",
    biography: "西格蒙德·弗洛伊德（1856—1939）是奥地利心理学家，精神分析学派的创始人。他提出的潜意识理论、人格结构理论（本我、自我、超我）和性心理发展理论，深刻影响了20世纪的心理学、文学、艺术和社会思想。",
    coreThoughts: "潜意识：人的心理活动大部分在潜意识层面进行，影响着我们的行为。人格结构：本我遵循快乐原则，自我遵循现实原则，超我遵循道德原则。梦的解析：梦是愿望的满足，是通往潜意识的皇家大道。",
    era: "modern",
    discipline: "psychology",
    region: "western",
    tags: ["精神分析", "潜意识", "心理学"],
    works: [],
    relatedWisePersonSlugs: [],
    wikipediaLink: "https://zh.wikipedia.org/wiki/%E8%A5%BF%E6%A0%BC%E8%92%99%E5%BE%B7%C2%B7%E5%BC%97%E6%B4%9B%E4%BC%8A%E5%BE%B7",
    personalIntroduction: "弗洛伊德是20世纪最具影响力的思想家之一，他的精神分析学说彻底改变了我们理解「人性」（Q08）的方式。在弗洛伊德之前，人类相信自己是理性的、自知的；弗洛伊德告诉我们——意识只是冰山一角，潜意识中的欲望、冲突和压抑才是驱动行为的真正力量。他的人格结构理论（本我、自我、超我）为理解人的内在冲突提供了经典框架。在通识学习的语境中，弗洛伊德的意义不在于他的具体结论（许多已被修正），而在于他开启了一个根本性的追问：人真的了解自己吗？这个追问至今仍是心理学、文学和艺术的核心议题。",
    questionNumbers: [8],
    topicCodes: ["8.3"],
  },
]

// ========== 问题 ==========
export const mockQuestions: Question[] = [
  {
    id: "q-1",
    code: "Q01",
    number: 1,
    title: "知识的知识",
    subtitle: "所有大问题的前置问题——关于知识本身的知识。认识论、方法论与创新学。",
    summary: "所有大问题的前置问题——关于知识本身的知识。认识论、方法论与创新学。",
    dimension: "meta",
    subTopicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    relatedWisePersonSlugs: ["plato", "aristotle"],
    relatedWorkSlugs: [],
  },
  {
    id: "q-2",
    code: "Q02",
    number: 2,
    title: "如何理解世界",
    subtitle: "世界观——认识我们所处的物质世界与生命世界。",
    summary: "世界观——认识我们所处的物质世界与生命世界。",
    dimension: "heaven",
    subTopicCodes: ["2.1", "2.2", "2.3", "2.4", "2.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-3",
    code: "Q03",
    number: 3,
    title: "如何理解历史",
    subtitle: "从历史中汲取智慧——理解文明的兴衰脉络。",
    summary: "从历史中汲取智慧——理解文明的兴衰脉络。",
    dimension: "heaven",
    subTopicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-4",
    code: "Q04",
    number: 4,
    title: "如何理解时代",
    subtitle: "时代诊断——识别我们所处时代的核心挑战与危机。",
    summary: "时代诊断——识别我们所处时代的核心挑战与危机。",
    dimension: "heaven",
    subTopicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-5",
    code: "Q05",
    number: 5,
    title: "如何理解社会",
    subtitle: "人类社会的基本运作逻辑——交换、交易、博弈与多样性。",
    summary: "人类社会的基本运作逻辑——交换、交易、博弈与多样性。",
    dimension: "earth",
    subTopicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    relatedWisePersonSlugs: ["karl-marx", "max-weber", "adam-smith", "rousseau", "aristotle"],
    relatedWorkSlugs: ["das-kapital", "communist-manifesto", "the-protestant-ethic", "the-wealth-of-nations", "social-contract"],
  },
  {
    id: "q-6",
    code: "Q06",
    number: 6,
    title: "如何理解组织",
    subtitle: "现代社会的组织逻辑——如何创建和管理组织。",
    summary: "现代社会的组织逻辑——如何创建和管理组织。",
    dimension: "earth",
    subTopicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-7",
    code: "Q07",
    number: 7,
    title: "如何理解家庭",
    subtitle: "人生最基本的亲密关系单元——从建立到告别。",
    summary: "人生最基本的亲密关系单元——从建立到告别。",
    dimension: "earth",
    subTopicCodes: ["7.1", "7.2", "7.3", "7.4", "7.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-8",
    code: "Q08",
    number: 8,
    title: "如何理解人性",
    subtitle: "人何以为人——从生理基础到文学表达的人性探索。",
    summary: "人何以为人——从生理基础到文学表达的人性探索。",
    dimension: "human",
    subTopicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-9",
    code: "Q09",
    number: 9,
    title: "如何理解身体",
    subtitle: "身体是灵魂的居所——身心健康与环境适应。",
    summary: "身体是灵魂的居所——身心健康与环境适应。",
    dimension: "human",
    subTopicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
  {
    id: "q-10",
    code: "Q10",
    number: 10,
    title: "如何理解信仰",
    subtitle: "超越性追问——理解不同文明的精神传统。",
    summary: "超越性追问——理解不同文明的精神传统。",
    dimension: "human",
    subTopicCodes: ["10.1", "10.2", "10.3", "10.4", "10.5"],
    relatedWisePersonSlugs: [],
    relatedWorkSlugs: [],
  },
]

// ========== 书单 ==========
export const mockBookLists: BookList[] = [
  {
    id: "bl-1",
    slug: "minimum-50",
    title: "最小限度书单",
    summary: "精选 50 本必读经典，覆盖天地人三大维度的通识教育核心书目。",
    description: "这份书单精选了 50 本对人类文明影响最为深远的经典著作，覆盖哲学、科学、文学、社会科学等多个领域，按照「天、地、人」三大维度组织，是构建通识知识体系的最佳起点。",
    type: "minimum",
    bookSlugs: [],
    workSlugs: ["the-republic", "critique-of-pure-reason", "the-origin-of-species", "dream-of-the-red-chamber", "tao-te-ching", "on-the-origin-of-inequality", "das-kapital", "communist-manifesto", "the-protestant-ethic", "the-wealth-of-nations", "social-contract"],
  },
  {
    id: "bl-2",
    slug: "philosophy-starter",
    title: "哲学入门书单",
    summary: "从古希腊到现代哲学，为哲学爱好者准备的入门阅读路径。",
    description: "这份书单为想要了解哲学的读者准备，从古希腊三杰到德国古典哲学，再到现当代哲学，循序渐进地构建哲学知识框架。",
    type: "theme",
    bookSlugs: [],
    workSlugs: ["the-republic", "critique-of-pure-reason"],
  },
  {
    id: "bl-3",
    slug: "science-classics",
    title: "科学经典书单",
    summary: "改变人类科学观念的里程碑式著作。",
    description: "收录了从哥白尼到达尔文，从牛顿到爱因斯坦等科学巨匠的代表作，见证科学观念的变革之路。",
    type: "theme",
    bookSlugs: [],
    workSlugs: ["the-origin-of-species"],
  },
]
